### ISSUE TITLE
[잠실 - 출결] 출결 안내문 부착

### ISSUE THREAD

**Issue by tsulocalize** [woowacourse/working-scholars#1]
개요 : 캠퍼스 내 출결 안내문을 부착하여 출석 체크 누락을 방지한다
기간 : 2024.05.07 ~ TBD
방법 : 잠실 캠퍼스 정문 앞에 있는 화이트 보드에 `출석체크` 안내문 부착 - 카피 담당

[크루 피드백 및 근로 회의를 통해 유지 여부 결정]

**Comment by Mingyum-Kim** [comment]
## [요약] 
출결 안내문을 부착 후 피드백 수합 인원 배정함. (종이, 카키) 

## [세부 내용] 
**설문 내용**
- 출석 독려 이미지를 보고 출석 체크에 대한 효과가 있었는지 ?
- 출석 독려에 대한 다른 방안에 대한 의견이 있는지 ?

**설문 방식**
주변 크루원 10명 내외, 총 20명에게 구두 혹은 디엠 등 자유롭게 진행 후 결과 공유

**설문 기간** 
5월 24일(금) 까지 취합 예정

**Comment by hjk0761** [comment]
## [설문 내용 정리]

### 1번 주요 사항 정리 - 출석 독려 이미지를 보고 출석 체크에 대한 효과가 있었는지?

- 대부분 효과가 없었다고 응답했다.
- 처음에는 눈에 들어와 효과는 있었지만 시간이 지나고 눈에 잘 들어오지 않았다.

### 2번 주요 사항 정리 - 출석 독려에 대한 다른 방안에 대한 의견이 있는지?

- 카드를 찍었을 때 자동으로 출석이 됐음 좋겠다. (혹은 조그만한 모니터 하나를 둬가지고 QR 코드를 주기적으로)
- 5분전과 1분전에 학교 쉬는 시간 종처럼 안내음이 나왔음 좋겠다.
- 구름이 만든 슬랙봇을 적극 활용하면 좋지 않을까 ? 실제로 효과를 본 크루가 있음.
- 위치기반으로 설정했을 때 저절로 알람이 오는 것이 효과가 있었음.
- 각자 응답시트를 통해 자기가 출석을 제대로 했는지 확인
- 굿샷 강의장에 사용하지 않는 노트북 하나로 출석체크를 하라고 스크린, 스스로 시계 알람.

**Comment by hjk0761** [comment]
## [이슈 정리]

위 설문 결과를 바탕으로, 출석 독려 이미지의 효과가 없다고 판단해 유지보수를 하지 않기로 결정
