### ISSUE TITLE
[선릉 - 비품 관리] 비품 구매 요청 건의

### ISSUE THREAD

**Issue by alstn113** [woowacourse/working-scholars#103]
# 개요
원래 선릉 여자 화장실에 밀대 2개가 있었다고 합니다. 
추석 기간 이후 밀대가 1개만 남고 나머지 하나가 분실된 것 같습니다. 
추가적으로 밀대 물기를 짜는데 어려움이 있어 밀대 물기 짜개를 구매 요청드립니다.

# 구매 품목

https://www.coupang.com/vp/products/7567387665?itemId=19949882999&vendorItemId=70531363172&q=%EB%B0%80%EB%8C%80+%EC%A7%9C%EA%B2%8C&itemsCount=36&searchId=4e98d26710ba4f01bf56ad015bc308b8&rank=55&isAddedCart=

# 결론

밀대 1개, 밀대 물기 짜개 1개를 구매 요청드립니다.

# 기간
~ 2024.09.27

**Comment by woowahan-leah** [comment]
@alstn113 
요청해주신 밀대 주문해두었으니 이번주 중으로 캠퍼스에 도착하면 알려드릴게요!

**Comment by alstn113** [comment]
2024년 9월 26일 12시 20분 수령했습니다.

밀대 + 탈수기 세트인줄 알았는데 탈수기와 걸레만 주는거였네요. 죄송합니다.
