### ISSUE TITLE
[선릉-문제해결팀] 선릉캠퍼스 싱크 선반 구매

### ISSUE THREAD

**Issue by lilychoibb** [woowacourse/working-scholars#104]
# 개요

선릉캠퍼스 싱크대 우측에 비치할 싱크 선반 구매를 요청드립니다.

# 내용
- [이전 이슈](https://github.com/woowacourse/working-scholars/issues/90)의 구매 검토가 진행되지 않은 것 같아 재요청드립니다 :) 
- [제품 링크](https://www.coupang.com/vp/products/8310269516?itemId=23979038428&searchId=feed-c1815b7d8f3b4dde87d3c8e40685749b-view_together_ads-P7614253988&vendorItemId=82801887440&sourceType=SDP_ADS&clickEventId=68634d70-771d-11ef-9da3-3d95309894ac&isAddedCart=) 입니다! (이전 이슈의 제품은 일시품절인 관계로 최대한 비슷한 제품을 선택했습니다.)

# 기간
~ 2024.09.27

**Comment by wisemuji** [comment]
@lilychoibb 이전 이슈를 확인하지 못했네요! 리마인드 감사해요 🙇 

혹시 어떤 목적으로 싱크 선반이 필요한지도 알려주실 수 있을까요?
선릉 캠퍼스에서 물품 보관이 필요한 경우 개인 사물함을 사용하고 있는데요, 싱크 선반을 비치함으로 인해 다른 크루의 물건과 본인의 물건이 섞이는 문제가 생기지는 않을지 우려도 됩니다.

**Comment by lilychoibb** [comment]
@wisemuji 
관련 배경은 이 [이슈](https://github.com/woowacourse/working-scholars/issues/79)에서 다루고 있는 것 같습니다! (캠퍼스를 이동하면서 담당 팀이 바뀌어서 파악이 쉽지 않네요 🥺)
그 중 아래 관련 내용과 [코치님의 답변](https://github.com/woowacourse/working-scholars/issues/79#issuecomment-2275145262) 첨부드립니다 🙂
### 싱크 선반
#### 배경

텀블러 등의 설거지를 한 후 선반에 두어 말리는 공간이 필요하다는 설문 응답이 있었습니다.
#### 진행 방식

싱크 선반을 한 개 구매하여 싱크대 옆에 둡니다.
#### 기대 효과

물기가 묻은 용기를 선반에서 말린 후 들고 다니거나, 자신의 자리에 들고가서 말리는 등의 불편함을 해소할 수 있습니다.

**Comment by woowahan-leah** [comment]
@lilychoibb 자세한 정리 감사합니다 👍 

요청해주신 싱크 선반 주문해두었으니 이번주 중으로 캠퍼스에 도착하면 알려드릴게요!

**Comment by woowahan-leah** [comment]
@lilychoibb 아래와 같이 창고 오른쪽 구석에 보관해두었어요!

![image](https://github.com/user-attachments/assets/b130bba5-d3ba-473d-b46f-6e8772e55181)
