### ISSUE TITLE
[선릉-문제해결팀] 회의실, 페어룸 공간 사용 현황 점검

### ISSUE THREAD

**Issue by lilychoibb** [woowacourse/working-scholars#105]
# 개요

[해당 이슈](https://github.com/woowacourse/working-scholars/issues/102) 의 회의실, 페어룸에 대해 공간의 목적에 맞지 않게 사용되거나, 정해진 시간을 초과하여 사용하는 사례를 점검합니다.

#### 회의실
- 포함 공간: 금성 회의실, 수성 회의실, 목성 회의실, 화성 회의실
- 기록 대상
   회의와 스터디 목적이 아닌 경우 (ex. 개인 공부, 미션, 학습테스트)
   회의실 사용 목적을 파악하기 어려운 경우
   팀원들이 번갈아가며 연속으로 회의실을 예약하는 경우
#### 페어룸
- 포함 공간: 페어룸1, 페어룸2, 페어룸3
- 기록 대상
   페어 목적으로 사용하지 않은 경우(ex. 개인 학습, 미션)
   페어룸 사용 목적을 파악하기 어려운 경우
   특정 크루가 연속으로 페어룸을 예약하는 경우
#### 공통
코어 타임(10:00 - 18:00) 예약 기록에 한하여 점검하였습니다.
연속으로 공간을 사용한 경우에는 연속된 예약들을 한 건으로 묶어서 계산했습니다.
ex) 감자가 페어룸을 14:00 ~ 15:00, 15:00 ~ 16:00 와 같이 두 번 예약한 경우 연속 예약 한 건으로 취급합니다.

# 기간
~ 2024.09.25

**Comment by khabh** [comment]
`2024.09.03 ~ 2024.09.20` 동안 찜꽁 예약 기록을 확인하여 [공간 사용 현황 점검](https://docs.google.com/document/d/1B0yQQjQ2f2TadGVZyMhNkq8f7OueRPIIO67xgLXhA0o/edit#heading=h.pq4h3dph91ke) 문서에 작성하였습니다.
