### ISSUE TITLE
[잠실 - 총괄] 잠실캠 인수인계 문서 작성완료

### ISSUE THREAD

**Issue by ii2001** [woowacourse/working-scholars#108]
# 개요

잠실캠 인수인계 문서 작성 완료

# 기간
~ 2024.09.26

# 참고 사항

[WiKi](https://github.com/woowacourse/working-scholars/wiki/%EA%B7%BC%EB%A1%9C-%EC%97%85%EB%AC%B4-%EA%B0%80%EC%9D%B4%EB%93%9C)
최종 검토 한번 해주시면 감사하겠습니다!

[리프레시 패키지]
(https://github.com/woowacourse/working-scholars/wiki/%5B6%EA%B8%B0%5D-%EB%A6%AC%ED[…]ED%8C%A8%ED%82%A4%EC%A7%80-%EC%9D%B8%EC%88%98%EC%9D%B8%EA%B3%84](https://github.com/woowacourse/working-scholars/wiki/%5B6%EA%B8%B0%5D-%EB%A6%AC%ED%94%84%EB%A0%88%EC%8B%9C-%ED%8C%A8%ED%82%A4%EC%A7%80-%EC%9D%B8%EC%88%98%EC%9D%B8%EA%B3%84))

[레벨 2, 3 선릉 캠퍼스 공간, 비품, 청소 - 우주먼지]
[https://github.com/woowacourse/working-scholars/wiki/%5B6%EA%B8%B0%5D-%EC%B2%AD%EC[…]C%A3%BC%EB%A8%BC%EC%A7%80)-%EC%9D%B8%EC%88%98%EC%9D%B8%EA%B3%84](https://github.com/woowacourse/working-scholars/wiki/%5B6%EA%B8%B0%5D-%EC%B2%AD%EC%86%8C,-%EB%B9%84%ED%92%88,-%EA%B3%B5%EA%B0%84%EA%B4%80%EB%A6%AC(%EC%9A%B0%EC%A3%BC%EB%A8%BC%EC%A7%80)-%EC%9D%B8%EC%88%98%EC%9D%B8%EA%B3%84)

[레벨 3 방학식]
https://github.com/woowacourse/working-scholars/wiki/%EB%B0%A9%ED%95%99%EC%8B%9D-%EC%9D%B8%EC%88%98%EC%9D%B8%EA%B3%84-%EB%AC%B8%EC%84%9C

[포수타 팀]
https://github.com/woowacourse/working-scholars/wiki/%ED%8F%AC%EC%88%98%ED%83%80-%EC%9D%B8%EC%88%98%EC%9D%B8%EA%B3%84-%EB%AC%B8%EC%84%9C

[테코톡]
진행 가이드
https://github.com/woowacourse/working-scholars/wiki/%ED%85%8C%EC%BD%94%ED%86%A1-%EC%A7%84%ED%96%89-%EA%B0%80%EC%9D%B4%EB%93%9C
편집 가이드
[https://github.com/woowacourse/working-scholars/wiki/%ED%85%8C%EC%BD%94%ED%86%A1-%[…]%91-%26-%EC%97%85%EB%A1%9C%EB%93%9C-%EA%B0%80%EC%9D%B4%EB%93%9C](https://github.com/woowacourse/working-scholars/wiki/%ED%85%8C%EC%BD%94%ED%86%A1-%ED%8E%B8%EC%A7%91-%26-%EC%97%85%EB%A1%9C%EB%93%9C-%EA%B0%80%EC%9D%B4%EB%93%9C)

[도서관리팀]
https://docs.google.com/document/d/1aSBd_o188_c4VqbFTdEUVHBM6JQSPHGzGhYCl20iq0E/pub

[만능팀]
[https://github.com/woowacourse/working-scholars/wiki/%EC%84%A0%EB%A6%89-%EB%A7%8C%[…]D%8C%80-%EC%9D%B8%EC%88%98%EC%9D%B8%EA%B3%84-%EB%AC%B8%EC%84%9C](https://github.com/woowacourse/working-scholars/wiki/%EC%84%A0%EB%A6%89-%EB%A7%8C%EB%8A%A5%ED%8C%80-%EC%9D%B8%EC%88%98%EC%9D%B8%EA%B3%84-%EB%AC%B8%EC%84%9C)

[레벨 2, 3 선릉 캠퍼스 공간, 비품, 청소 - 우주먼지]
[https://github.com/woowacourse/working-scholars/wiki/%5B6%EA%B8%B0%5D-%EC%84%A0%EB[…]C%B2%AD%EC%86%8C-%EB%B0%8F-%EB%B9%84%ED%92%88%EA%B4%80%EB%A6%AC](https://github.com/woowacourse/working-scholars/wiki/%5B6%EA%B8%B0%5D-%EC%84%A0%EB%A6%89%EC%BA%A0%ED%8D%BC%EC%8A%A4-%EC%B2%AD%EC%86%8C-%EB%B0%8F-%EB%B9%84%ED%92%88%EA%B4%80%EB%A6%AC)

**Comment by woowahan-leah** [comment]
@ii2001 안녕하세요 하디! 인수인계 문서를 코치분들과 함께 검토했고, 전체적으로 몇 가지 피드백이 있어 남깁니다 🙂 
아래 내용을 검토 후, **11/12(화)까지** 반영해주시면 됩니다.

## 피드백 종합

- 현재는 구글 독스로 작성된 문서도 있는데요, 공통적으로 깃헙 위키에 작성(구글 드라이브, 노션 X)해주세요. 한 눈에 볼 수 있도록 [근로 업무 가이드](https://github.com/woowacourse/working-scholars/wiki/%EA%B7%BC%EB%A1%9C-%EC%97%85%EB%AC%B4-%EA%B0%80%EC%9D%B4%EB%93%9C)에 링크를 모아주시면 됩니다.
- 반복되는 동일한 형태의 업무와 단발성 기획이나 업무를 분리해주세요.
- 인수인계 문서에 작성자의 닉네임을 기록해주세요.
  - 7기가 작업 중 모를 때 물어볼 수 있습니다. (회사에서도 간혹 퇴사자에게 연락하는 경우가 생길 수 있듯이요 :))
- 7기가 레벨2 초반에 '근로 자체'에 대한 온보딩을 할 수 있는 문서를 추가해주세요.
  - 레벨2 초반에 업무 진행 과정에서 헤매는 시간을 줄이기 위한 문서입니다.
  - 근로 전체를 총괄하는 팀에서 작성할 수 있을 것으로 기대합니다.
- 근로 조직 내 팀 구성과 팀의 역할 설명 문서를 추가해주세요.

**Comment by ksk0605** [comment]
피드백 반영 현광 보고 드립니다. 

계속해서 말씀 주신 피드백들 전반적으로 반영하여 [근로 업무 가이드](https://github.com/woowacourse/working-scholars/wiki/근로-업무-가이드)에 업데이트하였습니다. 

현재 아래의 팀이 피드백 반영이 아직 안되어있는 상황인데 만약 오늘 오후 6시 안까지 반영이 안될 경우 제가 임의로 수정하도록 하겠습니다. 
* [청소 인수인계 문서](https://github.com/woowacourse/working-scholars/wiki/%EC%B2%AD%EC%86%8C-%EC%9D%B8%EC%88%98%EC%9D%B8%EA%B3%84-%EB%AC%B8%EC%84%9C)
* [비품 관리 인수인계 문서](https://github.com/woowacourse/working-scholars/wiki/%EC%84%A0%EB%A6%89-%EC%BA%A0%ED%8D%BC%EC%8A%A4-%EA%B4%80%EB%A6%AC%ED%8C%80-%E2%80%90-%EB%B9%84%ED%92%88-%EA%B4%80%EB%A6%AC-%EC%9D%B8%EC%88%98%EC%9D%B8%EA%B3%84-%EB%AC%B8%EC%84%9C)
* [도서 관리 인수인계 문서](https://docs.google.com/document/d/1ZEcd9nhuS9zfQybdw8p540LY-LDVgr0flMfakQYoAEM/edit)
* [공용 우산 인수인계 문서](https://docs.google.com/document/d/1R3_LpqIAinKX6vC4TPhEijXgKqUkOqgcgqiT_6Lv8r4/edit?usp=sharing)

확인해주시고 피드백 주시면 감사하겠습니다!

**Comment by woowahan-leah** [comment]
인수인계 문서 작성하고 소통하시느라 고생하셨습니다 👏  
7기에게 잘 전달하도록 할게요!
