### ISSUE TITLE
[전체] 최종 데모데이 지원 요청 - 데모데이 페이지

### ISSUE THREAD

**Issue by kang-hyungu** [woowacourse/working-scholars#111]
# 개요
이 작업을 통해 해결하려는 문제를 정의하세요.

# 기간
~ yyyy.mm.dd

# 방법
- [ ] 방법1

# 참고 사항

**Comment by kang-hyungu** [comment]
5기 우테코 참고
https://sites.google.com/d/1OMnpvM_BmtOzekLRDxSn6kxwpE5y0Ty4/p/1iUUAOgEjDC7ec88fU3_q27KLvJXY2u6L/edit

**Comment by kang-hyungu** [comment]
- [x] 담당자는 구글 사이트 메인을 꾸며야 한다.
  - [최종 데모데이 드라이브](https://drive.google.com/drive/folders/1HZ5d5Ee79dkSllV_1Z_sbaWQOjiUgtsq)에서 "우아한테크코스 데모데이 구글 사이트 템플릿" 문서 참고
- [x] 메인 페이지 이외에 팀 소개 페이지는 각 팀에서 작성하도록 안내한다.
- [x] 홍보 시작 전에 게시하여 외부에서 접근할 수 있도록 한다.
  - 10/18까지 완료한다.

**Comment by ii2001** [comment]
[6기 데모데이 템플릿 사본 링크](https://sites.google.com/d/1p9FQn9RnJZ5_X1X2nGjSFggPMC5LRmBm/p/1n3WrrCvtkkqAFbTxsxQ5erkI43tcRep_/edit)

**Comment by Largopie** [comment]
- 10월 16일 수요일에 라이트닝토크, 자리 배정 확정
- 10월 17일 목요일까지 페이지 완성 후 홍보팀에게 전달 예정

> 병목이 생기지 않게 기본적인 사항은 작성해두고 라이트닝 토크 발표자에게 작성하도록 유도

**Comment by Largopie** [comment]
## 최종 데모데이 배포 사이트

- https://sites.google.com/view/woowacourse-demo-6th/%ED%99%88
