### ISSUE TITLE
[선릉 - 청소 관리] 폐기 필요한 냉장고 음식물에 대한 처리 요청

### ISSUE THREAD

**Issue by hyeonji1220** [woowacourse/working-scholars#116]
# 개요
매주 월요일 냉장고에서 나온 주인이 없는 음식물에 대한 처리를 해야하는 상황이 종종 발생하고 있습니다.
청소 담당 크루가 개별적으로 처리하기가 어려워 청소원분께 처리를 요청하려고 합니다.
이 부분이 가능한지 아니면 다른 처리 방법이 있을지 문의드립니다.

# 기간
~ 2024.10.25

# 방법
- [ ] 매주 월요일 처리되지 않은 음식물에 대해 청소원 분에게 처리를 요청합니다.

# 참고 사항

**Comment by woowahan-leah** [comment]
@skylar1220 성담빌딩 건물은 원래 취식 금지가 원칙입니다. 미화 업체의 도움을 받기는 어려울 것 같아요.
매주 월요일 냉장고에서 나온 음식물은 음식물을 보관한 본인이 치워야 하지 않을까요? 🤔

**Comment by wmakerjun** [comment]
미화 업체에 음식물 처리 요청을 드리기는 어려울 것 같아요. 레아가 말씀해주신 것처럼, 음식물을 보관한 본인이 치울 수 있도록 최대한 가이드를 해야할 것 같아요.
