### ISSUE TITLE
[잠실 - 공간] 도서 관리 방안

### ISSUE THREAD

**Issue by khabh** [woowacourse/working-scholars#13]
## 1. 개요
- 잠실 캠퍼스 내 도서 관리 방법 고안한다.

## 2. 목적
- 크루들이 도서 이용 중 겪는 불편함 해소

## 3. 안건 및 세부 운영 계획 (크루들이 겪은 불편함)
- 책꽂이에 책들이 쓰러진 채로 있는 경우가 자주 발생 - [공간 관리 제보](https://woowacourse.slack.com/archives/C0711HRU3S6/p1714372954794709)
  - 청소 체크리스트에 흐트러진 도서 정리 항목 추가
  - 북스탠드 추가 구매 (현재 7개 보유)
- 책을 정리할 때 정확히 어느 위치에 놔야 할지 헷갈림
  - 각 도서에 카테고리 스티커 부착하여 책을 분류

## 4. 문의 사항
- 해당 운영 계획에 대한 코치님들의 피드백
- 손상된 책 발견 시 코치님들에게 전달 시 도움을 받을 수 있는지 궁금합니다

**Comment by zangsu** [comment]
#35, [도서 관리 마일스톤](https://github.com/woowacourse/working-scholars/milestone/2) 으로 이동하였습니다.
