### ISSUE TITLE
[선릉 - 게시판] - 공용 우산 관리

### ISSUE THREAD

**Issue by Hain-tain** [woowacourse/working-scholars#15]
안녕하세요, 대숲지기(게시판 관리)팀입니다.

지난 4월, 제이슨께서 슬랙으로 공용우산에 대해 언급하신 적이 있습니다.

<img width="582" alt="스크린샷 2024-05-17 오후 4 57 04" src="https://github.com/woowacourse/working-scholars/assets/157036488/b9a51b7d-023f-4dbb-9f07-f2daad81a44b">

그래서인지 공용 우산과 관련하여 두 가지 문의가 들어왔습니다.

1. 공용 우산 꽂이로 사용하려는 첫번째 칸이 맨 오른쪽인지, 맨 왼쪽인지 모르겠다.
2. 공용 우산이면 써도 되는가?

이에 대해 명확한 가이드가 있으면 좋을 것 같아, 가이드 설정 및 안내에 대해 문의드리고자 합니다.

또한 만약, 공용 우산을 다 같이 쓸 수 있게 한다면, 공용 우산 대여 시스템에 대해 규칙을 세우고, 안내하고자 합니다.

[대숲지기에서 생각한 공용 우산 꽂이 및 공용 우산 사용 가이드]

1. 사진상 맨 왼쪽 우산꽂이를 공용 우산 꽂이로 사용한다. (공용 우산 꽂이함에 `공용 우산`이라고 적어둔다.)
2. 공용 우산에 공용 우산 라벨링 또는 스티커를 붙여 공용 우산임을 체크한다.
3. 개인의 양심에 따라 공용 우산을 사용하면 다음 날, 공용 우산 꽂이로 스스로 반납한다.

**Comment by wmakerjun** [comment]
공용 우산 꽂이를 구분하는 관점 너무 신박한데요!? 공유 우산 공간이란 것이 명확하게 보이게끔 시각적인 장치만 하나 마련하면 좋겠네요 👍🏻

**Comment by woowahan-leah** [comment]
👍  좋습니다
라벨링용 종이를 프린트하고 싶으시면 코치에게 요청해주세요!
