### ISSUE TITLE
[잠실] 근로 방향성 논의

### ISSUE THREAD

**Issue by pricelees** [woowacourse/working-scholars#16]

**Comment by hyeonji1220** [comment]
# 업무 상황 공유 방식

1. 현재 방식: 이슈, 주별 회의록 대표 수합 

단점: 불필요한 수합 과정 필요

1. 개선 방안

대표자가 수합하는 게 아니라

이슈로 관리

# 방안: 깃 활용

## 이슈 세분화

이슈를 보는 것 만으로 todo와 done을 파악할 수 있다면

## 보드 활용 (이슈 모음)

그걸 한눈에 볼 수 있는 곳이 프로젝트 - 보드

### 이슈, 보드만 보고 수합과정 필요없이 코치가 주별 업데이트를 파악할 수 있게 하자.

## 코치가 이슈 요청  → 근로의 이슈 티켓팅으로 이어지게

- 이슈 요청 템플릿: ~~ 업무 요청합니다.라는 이슈 템플릿 필요
- 이슈 티켓팅이란: 요청을 보고 협의 후 담당 근로 팀이 업무를 확정하여 assignment가 되어야만 이슈를 발행하는 것

# 변화: 팀별 회의 수합하는 대표 역할 필요 없어짐

**Comment by hyeonji1220** [comment]
# 추가: 주 1회 고정 업무 시간(정기회의?)의 필요성

목적

1. 현재 주어진 업무가 익숙해진다면, 업무량 적다는 내부 성찰
2. 그때 필요한 건, 이벤트 바리에이션 
3. 꼭 전체 회의라기보단, 고정된 업무 시간으로 활용하는 목적으로
4. 어떻게든 일단 모여서, 배정된 역할이 있는 사람들은 그 업무를 하고, 유휴 인원은 다른 일을 모색하는 시간

이 추가 회의, 고정 업무 시간이 필요하다는 말이 나오게 된 이유는 아래.

# 고민: 근로이지만 하는일이 적다는 내부 성찰

근로를 지원할 때 근로를 통해 무엇을 하고자 하며 지원했는지 떠올려보기

**Comment by Mingyum-Kim** [comment]
[이벤트 바리에이션에 대한 의견]

2024-05-24 회의에서 이슈 발행에 관하여 나온 의견입니다.

1. 
일이 배정되지 않은 유휴 인원이 이벤트 바리에이션의 역할을 맡기. 
- 근로 인원들이 지속적으로 이슈를 발행한다. 유휴 인원은 정기 회의를 통해 해당 이슈에 대해 논의하고 인원을 배정한다.

2.
이벤트 바리에이션 팀을 따로 만들기
- 유휴 인원은 유휴 인원대로 두고, 이벤트 바리에이션 팀을 따로 둔다.
