### ISSUE TITLE
[잠실] 이슈 템플릿 확정 및 공유

### ISSUE THREAD

**Issue by tsulocalize** [woowacourse/working-scholars#17]
**개요**
이슈 발행 시 템플릿 부재로 인해 통일되지 않은 형태를 가지게 되고, 각 이슈 내용을 파악하기에 어려움이 존재함.

**수행 방식**
이슈 템플릿 결정 및 잠실 근로 인원에게 공유 / 사용 요청

**기한**
2024-05-24 잠실 근로 전체 회의 시

**Comment by hyeonji1220** [comment]
# 코치 요청 이슈
## 템플릿
당장 필요하지 않음

## 코치 요청 이슈 응답 방식
코멘트에 구체적으로 어떻게 업무를 진행할지 적는것 (x)
아래 정도로만 적기(o)

`확인 후 이슈 발행하였습니다.` [이슈 링크](url)

##  피드백 요청 방식
- (근로) 피드백 요청: 해당 카테고리로 피드백을 원하는 이슈를 옮겨놓고, 슬랙에 코치 멘션 + 이슈 링크를 적어 쓰레드를 만듭니다.
- (코치) 피드백 응답: 코치들은 이슈에 피드백을 적어주시고 해당 쓰레드에 답글로 ‘답변 남겼습니다’ 남겨주면 됩니다.

## close 처리
이슈 발행 후 assignee가 close하기

**Comment by ksk0605** [comment]
[ 근로 이슈 템플릿 ]

# 개요
이 작업을 통해 해결하려는 문제를 정의하세요.

# 기간
~ yyyy.mm.dd

# 방법
- [ ] 방법1

# 참고 사항
