### ISSUE TITLE
[잠실 - 업무 컨벤션] 프로젝트 페이지 활용 방안 논의

### ISSUE THREAD

**Issue by pricelees** [woowacourse/working-scholars#18]
### 개요
[현재 근로 프로젝트 페이지](https://github.com/orgs/woowacourse/projects/9)는, `TODO, In Progress, Done` 세 가지의 컬럼으로 구성되어 있습니다. 

금일 프로젝트 페이지 활용 방안에 대한 논의 과정에서, 몇 가지 Column을 추가하는 것에 대한 의견이 있었고, 이외의 프로젝트 페이지의 활용 방안에 대해서도 논의해보고자 합니다.

### 일정 및 방법
- **5월 24일(금) 오후 3시 전체 회의**에서 논의
- 논의가 필요한 사항은 해당 이슈 페이지의 댓글로 작성

#### 1.코치분들에게 피드백을 요청하는 컬럼, 피드백이 완료된 컬럼이 추가되면 좋을 것 같다

**배경**
- 코치의 피드백 없이 바로 진행이 가능한 업무가 있고, 피드백이 있어야 진행이 가능한 업무가 있음. 

**기대**
- 코치분들이 피드백이 필요한 업무를 일괄적으로 파악할 수 있게 되어 업무 진행이 더 효율적으로 될 것으로 기대 

#### 2. Weekly TODO, DONE 컬럼 추가

**배경**
- 큰 틀에서 진행되는 업무가 있고, 짧은 기간동안 진행되는 세부적인 업무들이 있는데 같은 컬럼에 있게 되면 해당 주간동안 해야할 업무 파악이 힘들 것임.

**기대**
- 큰 틀에서 진행되는 업무와, 매주마다 진행되는 세부적인 업무를 구분하여 업무 파악이 수월해질 것으로 기대

**Comment by hyeonji1220** [comment]
# 카테고리 세분화
1. not assigned
2. todo
3. in progress
4. hey coach
  - 우리가 코치에게 피드백을 요청한 것
  - 우리가 코치한테 요청할 때 쓴 쓰레드에 코치가 코멘트로 '답변 남겼습니다' 남기기
5. weekly done
6. done 
  - 우리는 그때그때 weekly done으로 옮기고, assignee가 일주일 지난 것 같으면 done으로 넘기기.

**Comment by hyeonji1220** [comment]
# 확정 방안 공지 
assignee 중 한 명이 담당하여 안내문 작성

1. 마일스톤으로 관련 이슈 묶기 - 상돌
2. 카테고리 기준 정리하기 - 커비
