### ISSUE TITLE
[선릉, 잠실] 레벨2 방학식 기획/운영 요청 (~6/4까지)

### ISSUE THREAD

**Issue by woowahan-leah** [woowacourse/working-scholars#19]
### 개요    
- 레벨2 방학이 다가오고 있습니다. (6/14 방학식)
방학식 당일에 각 캠퍼스별로 어떻게 진행할지 기획과 운영을 요청드립니다.
- 단, 레벨1 방학식처럼 회고를 진행하지는 않습니다.  방학식만 즐겁게 기획해주세요~ 🤸‍♀️

### 기간
- 6/4까지 진행 방법과 타임라인을 공유해주세요.

### 방법    
- 사전에 공유된 [5기 피플행복 근로 폴더](https://drive.google.com/drive/u/0/folders/16-6OeNvz-ziljJOkcM9YPLYDk_AskgyX) 를 참고해주세요.

**Comment by solarsalt** [comment]
**참고 자료 전달**
5기 레벨1 방학식 간략한 행사 기록 공유해드립니다. 
각 캠퍼스별로 2명의 코치가 기획, 진행했었습니다.

참고로, 우테코 방학식은 매 기수, 매 레벨마다 각 시점에 맞는 다른 컨텐츠로 진행되었습니다.
이전 기수의 진행내역은 참고만 하시고, 완전히 새로운 형식으로 기획하셔도 됩니다. 

잠실 

> 우테코 어워즈
> 오프닝 공연 /  어워즈 축하 공연
> 오프닝 (15분)
> 퀴즈 5가지
> -연극일자 
> -미션 갯수
> -레벨1 담당자가 가장 강조하고 싶은 단어 2개 초성 맞추기
> -각 과정별로 리뷰어 코멘트 갯수
> 우테코 어워즈(20분)
> -선정 이유 → 상 이름 → 누구입니다. 수상자 인터뷰 받기(3분 * 4명)
> -마지막 상만 토크쇼(5분)
> 코수타(15분)
> 브라운 정리 멘트
> 방학 일정 공지 및 마무리(5분)


선릉
우퀴즈 온더 블럭

> - 오프닝 (10분)
> 
> - 토크쇼 & 퀴즈 (40분~60분, 각 5~10분)
>   - 우지컬: 100 우승자
>     - 우승을 위해 특별히 준비한 것이 있는지? (훈련, 마음가짐)
>     - 결승전에서 씨름 or 휴지 대결을 하며 어떤 생각이 들었는지?
>     - 다음 대회에도 나올 건지? 1대 우승자로서 참가자들에게 한마디
>     - 크루 스토리
>   - 글쓰기 우수작
>     - 자기 작품 간단 소개
>     - 글쓰기를 하면서 힘들었던 점?
>     - 글쓰기를 하면서 배웠던 점?
>     - 감명 깊었던 글귀, 책
>     - 크루 스토리
>   - 일취월장 크루
>     - 레벨1 시작과 지금을 비교했을 때 어떤 부분이 성장했다고 생각하는지?
>     - 어떤 방법으로 이렇게 성장했다고 생각하는지?
>     - 같은 고민을 했던 크루가 있다면 하고 싶은 말
>     - 크루 스토리
>   - 함께 자라기
>     - 어떤 이유 때문에 선정되었다고 생각하는지?
>     - 왜 그런 행동을 했는지?
>     - 그렇다면 앞으로는 어떻게 하고 싶은지?
>     - 크루 스토리
>   - 최고의 짝꿍
>     - 누가, 왜 추천한 것 같냐?
>     - 짝꿍 자랑 타임: 내 짝꿍은 이런 점이 정말 좋았다.
>     - 짝꿍 디스 타임: 내 짝꿍은 이런 점이 조금은 아쉬웠다.
>     - 크루 스토리
>   - 너는 감동이었어!
>     - 누가, 왜 추천한 것 같냐?
>     - 질문2
>     - 크루 스토리
>     - 레벨1을 마친 크루에게 하고 싶은 말
>   - 코치 초청석
>     - 크루 질문1
>     - 크루 질문2
>     - 레벨1을 마친 크루에게 하고 싶은 말
> 
> - 제이슨 정리 멘트(5분)
> 
> - 클로징 (5분)

**Comment by woowahan-leah** [comment]
선릉 후속 이슈: https://github.com/woowacourse/working-scholars/issues/47
잠실 후속 이슈: https://github.com/woowacourse/working-scholars/issues/43
