### ISSUE TITLE
[잠실 - 출결] 출석 꿀팁 안내 가이드 공유

### ISSUE THREAD

**Issue by tsulocalize** [woowacourse/working-scholars#2]
개요 : 크루들의 `출석 꿀팁 안내 가이드`를 공유하여 출석 체크 누락을 방지한다
기간 : 안내 가이드 완성 후 일주일 내
방법 : `출석 꿀팁 안내 가이드`를 작성 후 알쓸크잡 및 슬랙 채널 공지를 통해 크루들에게 공유한다

**Comment by hjk0761** [comment]
## [요약] 
테바 - 출석 꿀팁 안내 가이드 작성 진행 중

## [세부 내용] 
**진행 사항**
- 출결 꿀팁 안내 가이드 작성 중
- 알쓸크잡 권한 받은 이후 업로드
- 업로드 이후 슬랙에 공지

**공유 기간** 
5월 24일(금) 까지 공유 예정

**Comment by Mingyum-Kim** [comment]
## 결과

아이폰 및 갤럭시에 대한 출석 꿀팁 가이드 제작 후 6기-잡담 채널에 공유 완료함.
