### ISSUE TITLE
[선릉 - 게시판] 온라인 게시판 운영 방식 공유

### ISSUE THREAD

**Issue by 00kang** [woowacourse/working-scholars#20]
### 1. 온라인 게시판 구글폼
[구글폼 바로가기](https://docs.google.com/forms/d/e/1FAIpQLSfCdCjfsPmDj-i4ZZT6KYYyGDyAcJYsPrLzy3IJHLjpy9IvDg/viewform?usp=send_form)

### 2. 온라인 게시판 운영 방식

- 24시간 오픈되어 있기에 크루들은 언제나 문의 혹은 이벤트 공유가 가능합니다.
- `전 주차 수요일부터 해당 주차 화요일` 까지 질문을 수집합니다.
- `해당 주차 수요일`에 근로팀(대숲지기팀) 끼리 질문을 정리합니다
  - 코치의 의견이 필요한 경우에는 **근로 깃허브 이슈** 혹은 슬랙 **6기-근로** 채널로 질문을 전달합니다.
- `해당 주차 금요일`에 게시판을 통해 크루들에게 답변을 공유합니다.

### 3. 온라인 문의 답변 방식

- A4용지에 답변 정리해서 게시판 위치에 부착합니다.
- 필요에 따라 슬랙 **6기-캠퍼스-선릉** 혹은 **6기-잡답** 채널에 공유합니다.

### 4. 답변 공유 게시판 위치
- 게시판 종이 사이즈가 A4로 바뀌게 되면서 게시판 위치를 책꽂이 옆면으로 변경했습니다. 
  <img src="https://github.com/woowacourse/working-scholars/assets/70834044/8edf7604-93a4-46aa-a3d7-03ed7604914b" width="300px"/>

**Comment by imakerjun** [comment]
굿굿굿 좋습니다! 진행해 보시죠!!

**Comment by 00kang** [comment]
게시판 운영 방식 재선정으로 인한 혼선을 방지하기 위해 close합니다!
