### ISSUE TITLE
[잠실 - 메타인지] 메타인지 스터디 일정 수요조사

### ISSUE THREAD

**Issue by ay-eonii** [woowacourse/working-scholars#21]
**개요**
메타인지 스터디 기존 일정에 대한 수요조사를 받는다.

**수행 방식**
잠실캠 메타인지 스터디 크루들을 대상으로 메타인지 스터디 일정 수요조사를 슬랙으로 진행한다.
일정은 [월, 화, 수, 목, 금] 을 대상으로 한다.

**기한**
5/27(월) 18:00 까지

**Comment by alstn113** [comment]
<img width="908" alt="image" src="https://github.com/woowacourse/working-scholars/assets/75781414/c8d7f6b5-fbab-4ef5-a25b-dc990a345416">

월요일: 15명 (시소, 리브, 카고, 몰리, 다온, 배키, 비토, 콜리, 켬미, 타칸, 커비, 마크, 폰드, 백호, 낙낙)
화요일: 1명 (몰리)
수요일: 0명
목요일: 1명 (미아)
금요일: 3명 (배키, 프룬, 테니)
