### ISSUE TITLE
[잠실 - 도서 관리] 도서 카테고리 분류를 위한 필요 물품 파악

### ISSUE THREAD

**Issue by zangsu** [woowacourse/working-scholars#23]
# 개요

잠실 캠퍼스 내 도서 카테고리 분류를 위한 필요 물품 구비

# 기간

~ 2024.05.31

# 작업 내용

- [x] 필요한 북 스탠드 수량 파악 후 코치님들께 요청
- [x] 카테고리 분류에 사용할 스티커 선택 후 코치님들께 요청

# 참고 사항

[comment](https://woowacourse.slack.com/archives/C06RGDY21K9/p1716442233460879?thread_ts=1716263651.229659&cid=C06RGDY21K9)

**Comment by J-I-H-O** [comment]
**도서 카테고리 분류 물품 현황**
- 현재 북 스탠드 개수: 8개

**카테고리 분류 필요 물품 목록**
- 필요 북 스탠드 개수: 5개
- 필요 스티커 종류: 총 11 종류
 - 각 카테고리 별 도서 수는 파악중
