### ISSUE TITLE
[잠실 - 포수타] 앞으로의 포수타 방향성 논의

### ISSUE THREAD

**Issue by nak-honest** [woowacourse/working-scholars#25]
## 개요
- 각 포수타를 진행하는 MC가 포수타를 준비하기 때문에 2 달에 한번 일을 하는 상황.
- [근로이지만 하는일이 적다는 내부 성찰](https://github.com/woowacourse/working-scholars/issues/16#issuecomment-2124168707)에 따라 업무량이 적다고 느낌.

위의 상황에 따라 앞으로의 포수타 방향성을 구체적으로 결정한 뒤, 
인원 축소 여부를 논의한다.

## 수행 방식
선릉 포수타 팀과 날짜를 정해 온라인 회의를 진행한다.

## 기한
5월27일(월) 18:00

**Comment by ehtjsv2** [comment]
## 논의 결과
* 선릉포수타팀 또한 포수타준비를 제외한 추가 업무는 없고 업무량이 다른 팀에 비해 적다는 의견에 동의함
* 포수타를 더 다채롭게 만들며 업무를 늘리기에는 기존의 포수타 목적성이 있기에 무리라고 생각 => 기존방향 유지
* 포수타 인원은 두 명으로 축소하고 인원이 더 필요한 다른 팀에 배정되는 것이 좋을 것 같다는 의견
  * 선릉은 지금 테코톡팀이 업무에 비해 인원이 부족함을 느끼고 있다고 함

## 코치님께
포수타 초기 인원 배정은 코치님께서 정해주신 일이기에 의견을 물어봐야 된다고 생각하여 공유합니다!

포수타 인원을 축소시켜도 괜찮을까요? 아니라면 다른 방안이 있을까요?

**Comment by seokhongkim** [comment]
@ehtjsv2 
도도 안녕하세요. 업무 진행하시는 과정에서 인원 배정은 근로 내부에서 논의하신 후 자유롭게 조정하시면 됩니다. 🙂 

최초에 캠퍼스별로 두 명을 요청드린 이유는, 한 명이 아픈 경우에도 포수타 진행에 문제가 없기 위함입니다.
따라서 인원을 재조정 하시더라도, 잠실 캠퍼스 담당자가 아픈 상황이 발생할 때 어떻게 대응할 것인지에 대해서도 계획을 세워두시면 좋겠습니다.

그리고 포수타의 진행 형식이나 내용도 일정 부분 변경할 수 있는데요.
담당하는 크루가 변경이 필요하다고 생각하시는 이유, 변경해보려는 방향을 정리해서 포비와 논의하여 결정하시면 됩니다.

(cc: @solarsalt @Wonmi91 @wmakerjun @woowahan-leah )

**Comment by nak-honest** [comment]
## 논의 결과
- 포수타 인원은 캠퍼스 별로 한 명씩 줄인다.
- 차출된 인원은 다른 팀으로 배정한다.
- mc가 아픈 경우에는, 남은 한 명이 mc 대리 업무를 수행한다. 소리 체킹, 모니터링은 차출된 인원이 수행한다.
