### ISSUE TITLE
테코톡 영상 편집 및 업로드

### ISSUE THREAD

**Issue by woowapark** [woowacourse/working-scholars#3]
### 개요
각 캠퍼스에서 진행 및 촬영한 테코톡 영상을 편집해서 우아한테크 유튜브 채널에 업로드합니다.     
총 139개 영상에 대해
- 테코톡 영상 컷 편집
- 테코톡 영상 자막 추가
- 테코톡 영상 썸네일 추가
- 우아한테크 채널에 업로드        

하는 업무를 포함합니다. 
### 기간    
- 테코톡은 레벨4 8주 차까지 진행됩니다. 
- 영상 편집 및 업로드는 기수 내에만 마무리될 수 있으면 그 기간 내의 일정은 자율적으로 결정해 주시면 되어요.
### 방법
- 인수인계: 구체적인 업무 가이드는 워니가 5/16(목)에 인수인계 해주실 예정 ([참고 문서](https://github.com/woowacourse/working-scholars/wiki/%ED%85%8C%EC%BD%94%ED%86%A1-%ED%8E%B8%EC%A7%91-&-%EC%97%85%EB%A1%9C%EB%93%9C-%EB%B0%A9%EB%B2%95) )) 
- 그 외 추가 문의는 테코톡 업무 전반에 관련한 문의는 저(공원)에게 해주세요. 
### 참고 사항
- 업로드 주기: 업로드 공해 방지(ㅋㅋ)를 위해 1회에 여러 개 업로드가 필요합니다.
  - 어느 요일에 / 어떤 주기로 / 한 번에 몇 개씩을 할 지는 전체 일정을 고려해서 근로 내에서 자율적으로 결정해주셔도 괜찮습니다. 
- 인원: 작년에도 테코톡 진행~편집 및 업로드까지 캠퍼스별 3명씩 총 6명의 크루가 담당해서 진행하였습니다. 참고 정보로 남겨두어요. 
## +) 이슈 만들어보면서 생긴 소소한 제안 사항
- [Issue Template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository)이 하나 있어도 좋겠다 싶었습니다! 🙂

**Comment by Wonmi91** [comment]
# 편집 시 참고 (특이사항)

## 3/14 선릉 > 깃 명령어 동작 원리 - 다르, 해시 발표
### 특이사항
- 1차 촬영본 : 화면 공유를 하지 않음
- 2차 촬영본 : 도중에 잠시 마이크 선이 빠진 상태로 진행

### 해결 방안 제안(편집 시 확인 필요한 부분)
- 2차 촬영본 상태를 확인하고 녹음이 빠진 부분이 있다면 재녹음 하는 방식으로 편집

## 3/28 선릉 > 동일성과 동등성 - 케이엠 발표
### 특이사항
- 화면 공유를 했으나 실제 발표 시 발표자용 화면이 공유됨 (시작하고 3~4분 지나고 인지하여 멈추기가 애매하였음…)

### 해결 방안 제안(편집 시 확인 필요한 부분)
- 화면의 특정부분(발표 자료)만 확대 혹은 자르기 하여 인코딩 (화질 저하 이슈 등 확인 필요)
- 아니면 화면은 녹화 되었으니 해당 화면에 맞게 발표자료를 캡처하여 편집

**Comment by kimhm0728** [comment]
@Wonmi91 

### 각자 한 주에 몇 개의 영상을 편집할 것인가?
- 한 명당 매주 최소 하나의 영상을 편집한다.
- 영상 업로드 일정에 맞춰서, 근로 크루 개개인이 유연하게 편집 일정을 조절한다.

### 각자 담당해서 편집할 영상 결정하기
- 근로 크루의 분야에 맞는 영상을 편집한다. (ex: 안드로이드 근로 크루는 안드로이드 영상 편집)

### 테코톡 업로드 주기
- 매주 월요일 2개, 매주 금요일 3개의 영상을 업로드한다. (일주일에 총 5번)
- 앞으로 업로드 될 영상의 개수, 편집된 영상의 개수 등에 따라 유동적으로 조절한다.
- 영상 139개 기준, 공휴일/방학에도 매주 올라간다고 가정했을 때, 매주 5개의 영상을 올린다면 11/25에 영상 업로드가 끝난다. (영상 편집본 여유분이 없거나 공휴일 등의 예외 상황을 대비하여, 일정을 빠듯하게 잡은 상태임)

### 테코톡 썸네일
- 기존 썸네일을 사용한다. 
- 4, 5기 모두 동일한 썸네일을 사용했기 때문에, 통일성을 가지고 가는 것이 좋겠다고 판단.

### 기타
- 첫 업로드 날짜 → 6/3일 (월)
- [테코톡 영상 편집 일정 시트](https://docs.google.com/spreadsheets/d/1UpseW6BgPxKON11uAlMpu6q0Hw-sVwCUrO6SN7bifK4/edit#gid=214731162)에 영상 편집 담당자와 영상 업로드 일정을 정리한다.
- 테코톡 편집 시 참고할 특이 사항
   - **<5/16>** AN_차람: 발표 도중 소리가 녹음되지 않음을 인지하고, 처음부터 다시 진행했음. 초반 2~3분 정도를 잘라야 함.
   - **<5/23>** AN_해나: 발표 도중 TV 연결이 끊겨서, 다시 연결했음. 중간 1분 정도를 잘라야 함.
