### ISSUE TITLE
[잠실 - 테코톡] 테코톡 영상 녹화 오류로 인한 처리 방안 논의 필요 (5/25)

### ISSUE THREAD

**Issue by BurningFalls** [woowacourse/working-scholars#34]
# 녹화 오류

### 특이사항

- 비디오(발표자 모습)만 녹화되고, 화면 공유(ppt)는 녹화되지 않음

### 특이사항

- 비디오(발표자 모습)만 녹화되고, 화면 공유(ppt)는 녹화되지 않음

### 특이사항

- 화면 공유(ppt)만 녹화되고, 비디오(발표자 모습)은 녹화되지 않음

---

# 처리 방안 논의 필요

* 해당 영상들에 대해 따로 처리 방법이 필요할 것 같아 문의드립니다.

**Comment by Wonmi91** [comment]
## 타칸 & 이상

타칸 & 이상의 경우 모두 화면공유 녹화가 되었는지 다른 파일로 살펴보았으나, 녹화가 되지 않았네요..!
이런 경우 어쩔 수 없지만, 발표자 모습이 녹화된 해당 화면 (즉 비디오)을 편집해서 올려주세요.
단, 이 경우 화면 공유 녹화가 되지 않아 발표자 모습이 크게 등장하기 때문에 각각의 크루들에게 공유하시고 양해를 구하시기 바랍니다.

## 로빈

로빈의 경우 발표자 모습이 녹화되었는지 확인했으나 역시 녹화가 되지 않았군요..!
녹화된 그대로 편집해서 올려주세요. 이 경우에도 로빈에게 공유하시면 좋을듯 합니다. 

## 공통 사항

테코톡 초반 녹화이기 때문에 이런 저런 이슈들이 많을 수 있습니다 : ) 
마이크 녹음이 잘 되지 않았다면, 볼륨으로 일정 부분 조절하시고 정확한 자막으로 대체하시는 것을 추천합니다.
화면이 제대로 녹화되지 않았다면, 녹화된 기준으로 방안을 찾아보시거나 혹은 크루들에게 재녹화를 요청할 수도 있습니다.
단, 정말 잘못 녹화된 경우가 아니라면 재녹화는 추천하지 않습니다..! 여러분들의 시간은 소중하니까요...!

제 의견을 남겨두나, 근로 내에서 논의 후 최종 결정을 부탁드려요~
더 좋은 방안이 있다면 그 방안으로 진행하셔도 됩니다.
추가로 저에게 먼저 의견을 구하시기 보다는 근로 내에서 어떤 식으로 결정을 했는지 공유해주시고, 코치들에게 의견을 물어보시면 더 좋을 것 같습니다~~!
