### ISSUE TITLE
우아한 게시판 프로젝트 진행 예정

### ISSUE THREAD

**Issue by seokhongkim** [woowacourse/working-scholars#40]

**Comment by 00kang** [comment]
안녕하세요 선릉캠퍼스의 게시판 관리, 대숲지기 팀입니다.
이미 다른 이슈를 발행하여 해당 프로젝트를 진행 중이기에 이 이슈는 close하겠습니다. !

[우아한 대나무숲 이슈 바로가기](https://github.com/woowacourse/working-scholars/issues/33)
