### ISSUE TITLE
근로 레벨2 회고 준비 요청

### ISSUE THREAD

**Issue by seokhongkim** [woowacourse/working-scholars#44]
## 개요

- 레벨2에 진행한 근로 업무를 되돌아보고, 레벨3에서 근로를 더 잘 하기 위해 회고를 진행하고자 합니다.
- 근로 업무에 참여한 크루와 근로 운영을 담당한 코치가 캠퍼스별로 모여서 진행할 예정입니다.
- 회고 준비와 진행은 근로 크루 주도로 이뤄집니다. 코치도 회고에 참석해서 크루의 주도 하에 근로 운영 업무를 돌아보는 시간을 가지려고 합니다.
- 자세한 내용은 아래의 회고에 대한 내용을 참고해 주세요.

## 업무 일정

- 6/5(수)까지 회고 일정, 장소, 진행 방법 결정 후 공유

### 회고 일정

- 회고는 6/12(수) 또는 6/13(목) 중 하루에 진행하고, 시간은 결정 필요

### 회고 장소

- 각 캠퍼스
  - 필요 시 무중력광장 / 트랙룸, 작은 강의장 공간 사용

### 회고 참석 인원

- 캠퍼스별 근로 장학생과 근로 운영 코치

### 회고 목적

- [근로의 목적](https://woowacourse.slack.com/archives/C06RGDY21K9/p1713250285459499)을 되돌아보면서, 레벨2에 진행한 근로 경험을 돌아보고, 레벨3에 어떻게 개선하여 진행하면 좋을지에 대해 작은 단위의 액션 플랜을 세워본다.
- 레벨2의 경험을 바탕으로 레벨3에 시도해보고 싶은 아이템을 이야기 나눈다.

#### 근로의 목적 (아래는 예시입니다)

- 우테코 공간을 좋은 학습 환경이 되도록 관리한다.
- 우테코에서 더 좋은 학습 경험을 만들 수 있도록 제안 및 개선을 한다.
- 우테코에서의 활동이 유의미한 기록물이 되도록 만든다
- 우테코에서 의도하지 않은 불편한 경험은 개선한다.
- 우테코 내에서의 효과적인 의사 결정을 할 수 있는 구조를 만들고 개선한다.

#### 기억해줬으면 하는 점

- 근로크루가 직접 궂은일(청소 등)을 하기 바라는 것은 아니다.
- 근로 활동이 과중해서 학습에 방해가 되기를 원하지 않는다.
- 근로크루가 비근로 크루의 일이나 문제를 무조건 대신 해결해주는 존재가 아니다.

### 회고 진행 시 참고 사항

- 레벨3는 팀 프로젝트 기간으로 잠실 / 선릉 캠퍼스의 인원이 무작위로 섞일 수 있습니다. 따라서 다음 레벨의 캠퍼스별 근로 크루가 참고할 수 있도록 구체적이고 실현 가능한 액션 아이템을 정하고, 정한 배경과 이유를 이해할 수 있도록 함께 정리해 주세요.

**Comment by hyeonji1220** [comment]
확인 후 이슈 발행하였습니다. [이슈링크](https://github.com/woowacourse/working-scholars/issues/46)
