### ISSUE TITLE
[잠실] 근로 레벨2 회고 준비

### ISSUE THREAD

**Issue by hyeonji1220** [woowacourse/working-scholars#46]
# 개요
레벨2에 진행한 근로 업무를 되돌아보고, 레벨3에서 근로를 더 잘 하기 위해 회고를 진행하고자 합니다.

# 기간
~ 2024.06.05

# 방법
5월 30일(목) 16시 회의 후 결과 댓글에 작성

**Comment by pricelees** [comment]
## 회의 결과
### 일정

- 6월 12일(수요일), 트랙룸
- 10:40 ~ (최대) 12:00 - 1안 / 14:00 ~ (최대) 15:20 - 2안

### 진행 방법

**1. 회고**

- 전체 회의 전에 전체 근로 크루를 대상으로 설문을 진행한다.
    - 설문 질문 선정
    - 단순히 회고만을 위한 설문이 아닌, 레벨3의 액션플랜 도출을 위한 질문을 선정한다.
- 설문을 통해 나온 내용을 바탕으로, 개선이 필요한 것을 선정한다.

**2. 액션플랜 도출**

- 이전 회고에서 나온 개선이 필요하다고 느껴지는 내용들을 구체화한다.
- 필요시 멘티미터 등으로 의견을 받을 수 있다.

**3. 레벨3에 시도해보고 싶은 업무**

- 설문에서 나온 내용을 공유한다.
- 설문에, 해당 업무를 정한 배경과 이유를 같이 작성한다.

### 세부 업무
- 설문: 상돌, 미아 
- 타임테이블: 테바, 커비
- 확정시 6/5(수) 까지 진행 예정

**Comment by pricelees** [comment]
## 코치 의견이 필요한 사항
- 회의 진행 시간 1안 / 2안 중 어떤 시간으로 진행할지
- 위의 **진행 방법**에 대한 추가 의견

**Comment by seokhongkim** [comment]
@skylar1220 @pricelees 
회고 일정을 먼저 확보하기 위해 진행 시간에 대해서 먼저 답변 드립니다.
- 2안 14:00 ~ (최대) 15:20 으로 진행 부탁드려요.

진행 방법에 대해서는 별도로 검토하고 의견 말씀 드릴게요.

cc: @solarsalt

**Comment by pricelees** [comment]
@seokhongkim 
[근로 크루를 대상으로 하는 설문](https://docs.google.com/forms/d/1VWqHYj6p1zszQcM3uORmUf7yjDXoccXEnz7A1FLXX6g/edit) 초안입니다. 진행 방법이 확정되면, 6기 근로 드라이브에 올리고 설문 진행하겠습니다!

**Comment by seokhongkim** [comment]
@skylar1220 @pricelees 검토 후 의견 드립니다!

- 회고 전에 설문을 통해 전체의 의견을 수렴해 보시는 것 좋습니다. 설문 결과를 회고 일정 전에, 모두가 읽어오게하면 당일 진행이 편해질 것 같아요 (참석자에게 숙제주기!ㅋㅋ)
- 설문을 통해 나온 내용을 바탕으로 바로 개선이 필요한 아이템을 선정하기보다는, 회고 시간에 문제나 해결책을 좀 더 구체화하는 시간을 가지면 좋겠습니다. 비슷한 내용처럼 보이더라도 각자가 문제라고 생각하는 내용이나, 해결책이 전혀 다를 수도 있습니다.
- 길지 않은 시간동안 진행하므로 적절하게 조를 나눠서(랜덤, 레벨1에 진행한 업무나 설문에 응답한 내용 등) 이야기를 나누고, 조별로 구체적인 아이템 하나라도 정해보는 것을 목표로 하면 어떨까요? 소그룹으로 하는 것이 얘기를 나누고 진행하기도 수월할 것 같아요.
- 많은 것을 개선하기 위해서 회고하는 것은 아닙니다. 레벨2에서 잘한 것이 있다면 다같이 확인하고, 계속 keep 하기를 합의하는 시간이 되어도 좋습니다.
- 회고를 6/12 수요일에 진행 예정이니, 설문 작성 기간(현재 6/5 수까지)을 조금 더 길게 가져가면 어떨까요?

cc: @solarsalt

**Comment by hyeonji1220** [comment]
## 타임 테이블
1. 설문 결과 모니터로 다같이 공유 (10분 소요)
2. 결과를 통해 선정한 토픽 3개를 갖고 소그룹 토론 (60분 소요)
   - 토픽별 문제점 또는 잘한점 및 액션플랜(문제라면 개선안, 잘했다고 생각한다면 유지방안) 도출
   - 결과를 멘티미터에 기록
   - 모든 그룹의 결과를 수합해서 토픽별 하나의 액션플랜 선정
   - 토픽별 20분 예상
3. 이외의 레벨 3에 시도해보고 싶은 업무 발표 (10분 소요)

**Comment by hyeonji1220** [comment]
## 6/5 2차 회의

1. 6/6 목요일동안 근로 크루 대상 설문 진행
2. 6/7 (금) 설문 결과를 갖고 토론 토픽 3개 구체화 및 멘티미터 준비

**Comment by hyeonji1220** [comment]
## 6/10 최종 회의

1. 설문 결과를 통해 토픽 추출
2. 구글폼 만들기: 테바
  - 각 토픽별 액션플랜 제출 * 3
  - 결과 투표 구글폼(틀만 미리 만들어놓기) * 3
3. 구글 슬라이드 제작: 커비, 미아 
 - 설문 결과는 어떻게 조별로 전달할까? 슬랙으로 쓰레드로 전달
4. 조 편성: 상돌

**Comment by jongmee** [comment]
## 구글 슬라이드
[링크](https://docs.google.com/presentation/d/1NlMIEQ-F-4XisLszwMJ387NlaJuTq0xQ1jCjvp7Zs-A/edit?usp=sharing)

**Comment by hyeonji1220** [comment]
6/12 레벨2 잠실 근로 회고 진행 쓰레드

**Comment by hyeonji1220** [comment]
**[토픽1]**

**긍정1: 불필요한 회의 감소**

* 업무 관리 담당이 생기고 불필요한 회의가 줄어들어서입니다.
* 불필요한 전체 회의가 잦지 않은 걸 보아 현재 의사 결정 과정이 효과적이라고 생각합니다
* 각 이슈에 대해 담당자가 할당되고 나면 추가적인 회의가 필요하지 않는 것이 좋다.

**긍정2: 자유로운 의견 제안**

* 자유롭게 의견을 내고 다양한 의견이 나오는 것, 그 사이에 의사결정이 잘되고 있다 생각합니다.

**긍정3: 소수 인원의 의사 결정**

* 소수 인원으로 빠르게 결정을 내리고 코치님들한테 피드백을 받는 프로세스가 좋다고 생각해서
* 팀별로 의사결정은 팀별 회의를 통해 잘 되고 있다고 생각한다.
* 사실 처음에 한 곳에 모여서 회의를 진행하는 방식이 소수의 의견대로 흘러간다는 느낌을 받았었는데, 지금은 근로를 어떻게 이어나갈 것인지에 대한 방향성이 잡힌 것 같다.


**부정1:**

안건 제안과 의사 결정에 대한 책임기구가 있지 않아 책임이 분산된 것 같다.

**Comment by hyeonji1220** [comment]
**[토픽2]**

**긍정1: 업무량**

* 아직은 업무가 적어서 적절하다고 생각합니다.

**긍정2: 이슈를 통한 업무 배정**

* 이슈를 파고 이슈를 할당받아 해결하는 프로세스가 마음에 든다.
* 이슈로 확인이 가능해 유휴인원을 관리하기에 효과적이라고 생각합니다.
* 칸반보드를 통해 소통하는 방식이 괜찮다고 느껴진다.
* 필요한 일에 하고 배정받고 싶은 사람이 배정받는 것이 효율적인 것 같음.

**부정1: 업무 배정 담당 인원의 필요성**

* 프로젝트를 통해서 유휴인원을 체크할 수 있고, 코치에게 업무 요청이 들어왔을 때 유휴 인원을 파악하고 있다가 업무를 배정하는 담당이 있으면 좋을 것 같다. 현재는 공간 관리 팀장들이 이 역할을 어쩌다보니 맡아하고 있는 느낌이 든다.

**Comment by hyeonji1220** [comment]
**자유 논의**
* (현재 있는지 모르겠지만) 누가 어떤 일을 맡고 있는지 한눈에 볼 수 있는 변동 가능한 자료(ex.시트)가 있으면 좋을 것 같다. (데이터 변경 인원 따로 배정 or 본인이 직접 수정)
* 총괄 조직의 부재
* 근로 인원 간 소통이 원활하지 않다.
* 체계적이지 않은 업무 분담 및 기록
* 필요한지에 대한 고민이 필요하나, 팀별로 진행 상황이 전체적으로 어떻게 돌아가는지 가끔가다 한번씩 파악되면 좋겠다는 생각이 들었습니다.
