### ISSUE TITLE
[우주방귀 팀] - 방학식 기획

### ISSUE THREAD

**Issue by Largopie** [woowacourse/working-scholars#47]
# 우아한 한 문장

## 🎯 진행하는 취지

- **유강스 조끼리의 레벨2 학습을 돌아보는 시간을 갖고, 유의미한 시간을 보내기 위함**

## 📚 미션 진행 방법

https://docs.google.com/spreadsheets/d/1p1PxMQyqCs08HKTku-tRJuD1-MMdLwrAXb7we3QV3Rs/edit?usp=sharing

## ⏰ 타임라인
[11 : 00 - 11 : 30] ⇒ 개인적으로, 레벨 1 방학식 때 세운 계획과 레벨 2 나의 실제 모습 비교하기
레벨1 방학식에 진행한 슬랙 예약 메시지 리마인더 활용하기
[11 : 30 - 12 : 15] ⇒ 유강스 조원끼리, 비교 내용 공유하기 + 유강스 조원끼리, 레벨 2 한정 서로의 모습을 한 문장으로 정리해주기
⇒ 스프레드 시트 활용하기
[12 : 15 - 13 : 45] ⇒ 점심시간
⇒ 점심시간의 의도 전달하기, 밥 먹으면서 어떤 대화를 했으면 좋겠는지
⇒ 긴 시간인 만큼, 의도가 있다.
[13 : 45 - 14 : 30] ⇒ 레벨 3에 되고싶은 내 모습 한 문장으로 정리하기
[14 : 30 : 15 : 00] - 사물함 정리, 냉장고 정리 ⇒ 마지막 활동

## 준비 물품
- 마지막에 레벨 3에 되고싶은 내 모습을 한 문장으로 정리해 지속적으로 리마인드할 수 잇도록 사물함/노트북에 포스트잇에 작성해 부착할 예정입니다! 따라서 **포스트잇, 펜**이 필요합니다!

**Comment by wmakerjun** [comment]
질문 2개에 한꺼번에 답변 드리면, 코치의 도움 없이 여러분들 스스로 기획, 실행, 진행까지 하면 됩니다~! 
만약 진행 하는데 있어 고민 되는점이 있다면 의견을 물어봐도 괜찮지만, 전적으로 여러분의 주도로 진행하는 것으로 생각해주면 될 것 같아요.

**Comment by Largopie** [comment]
@wmakerjun 
답변 감사합니다 :) ☺️

일찍 방학식을 마치는 것에 대한 수요, 그리고 방학식의 장소의 제약있는지에 대한 궁금증이 있어서 추가적으로 질문을 드리고싶습니다!

1. 방학식에 무조건 선릉캠퍼스에서만 진행해야하는지 궁금합니다. (ex. 한강, 온라인 등)
2. 방학식이 끝나야되는 시간이 정확히 정해져있는지 궁금합니다.

추가회의를 위해서 가능하면 오늘까지 답변주신다면 좋을 것 같습니다!

**Comment by wmakerjun** [comment]
@Largopie 

**1. 방학식에 무조건 선릉캠퍼스에서만 진행해야하는지 궁금합니다. (ex. 한강, 온라인 등)**
네~! 선릉캠퍼스에서 진행하는 걸로 기획 및 진행해주세요.

**2. 방학식이 끝나야되는 시간이 정확히 정해져있는지 궁금합니다.**
3시 이전에 끝나게 해주시면 됩니다~!

**Comment by Largopie** [comment]
답변 감사합니다 :) 추후에 회의 후 다시 확인 요청 드리겠습니다!

**Comment by woowahan-leah** [comment]
@Largopie 안녕하세요 낙타. 제안해주신 기획 관련하여 몇 가지 여쭤볼 것이 있습니다.

코치측에서 여러분들 스스로 기획, 실행, 진행까지 주도해서 진행해달라고 요청을 드렸었는데요,
제안해주신 활동을 보면 충분한 고민 이후에 정리한 기획이 맞는지 의문이 들어서요. 🤔 

### 아직 기획이 구체화되기 전에 리뷰를 요청하신 것인지?

전달해주신 내용만으로는 방학식에서 구체적으로 어떠한 활동을 하시려는 것인지 파악하기 어렵습니다.
미션 형태로 타임라인/회고를 작성한다고 작성해주셨는데, 어떤 미션이 있는지도 알 수 없어서요.
활동 마지막에 시상 계획도 있는데 구체적으로 몇 팀을 시상하는 것인지, 투표 기준은 무엇인지도 구체화해주시면 좋을 것 같아요.

### 방학식이 끝나고 난 뒤 크루들이 어떤 상태이길 바라는지?

이전에 방학식 활동 기획에 대한 의도를 알려달라고 부탁드렸었는데요,

> 활동 자체는 의미있다고 생각하는데요. 타임라인 작성, TMI 맞추기 게임이 각각이 어떤 의도를 담고 있는지를 이야기해주면 좋을것 같아요. 아마 교육 분야별로 레벨에서 학습한 내용을 다뤄볼수도 있는데요.
그렇다면 타임라인을 그림으로 인해서 우리가 어떤 이야기를 더 나눴으면 하는 건지
TMI를 맞춤으로써 코치, 크루간에 더 친해지는걸 의도하는 건지
이런 의도를 작성해주면 더 의미있는 피드백을 줄 수 있을것 같아요!

막상 알려주신 것은 피그마로 활동을 진행하는 취지를 알려주셨어요. 😓 
사실 저희가 알고 싶었던 것은 활동 자체의 목적이지, 어떤 수단을 통해 활동을 진행하는 것인지가 아닙니다.

> 취지 : 종이는 사라져서 아쉬웠고, 더 예쁜 디자인으로 오래 소장할 수 있게끔 피그마로 타임라인 정리 진행

타임라인을 그림으로 인해 유강스 조끼리의 레벨2 학습을 돌아보는 시간을 갖길 원하시는 걸까요? 회고를 하며 친목을 다지길 원하시는 걸까요? 방학식을 진행하실 때에도 크루들에게 이 활동의 의도를 알려주셔야 할 것 같습니다. "세상에서 제일 예쁘게 회고하기"라는 제목만으로는 이 활동의 목적을 이해하기 어렵습니다.

cc @wmakerjun

**Comment by Largopie** [comment]
@woowahan-leah

조금 더 구체적으로 기획안을 작성했어야 했네요 😅
먼저 상세하고 구체적으로 피드백 남겨주셔서 감사합니다.☺️

궁금하신 부분에 대해서 답변드리겠습니다.

> 아직 기획이 구체화되기 전에 리뷰를 요청하신 것인지?

기획이 구체화되기 전에 리뷰를 요청한 것이 맞습니다. 어떻게보면 "방학식 기획, 운영, 진행 모두 관리해야한다" 에 대한 지침이 정확히 없어서 저희끼리 정하는데 방향성이 잡혀있지 않다고 생각이 들었어요. 그래서 지속적으로 질문 및 답변을 해나가면서 기획을 구체화하고 싶었습니다.

저번에 기획에 같이 제안했었던 퀴즈같은 경우에서도 기획에 관련된 부분만 하면 된다고 생각을 했었는데, 실제로 진행을 해야하다보니 방학식 기획 팀은 참여하기 어렵겠다는 생각도 들었었구요..! 그래서 궁금해하는 부분에 대해서 최대한 질문 및 답변을 하면서 지속적으로 괜찮다는 답변을 받았을 때 구체화하려고 계획하고 있었습니다!

> 막상 알려주신 것은 피그마로 활동을 진행하는 취지를 알려주셨어요. 😓
사실 저희가 알고 싶었던 것은 활동 자체의 목적이지, 어떤 수단을 통해 활동을 진행하는 것인지가 아닙니다.

이 부분은 이해를 잘못한 것 같네요 🥲. 아무래도 우테코에서 지향하는 방향성이 피드백과 회고와 같은 부분을 중시하다보니 단순히 막연한 게임보다는 지향점에 맞는 취지에 대해서 생각을 해보았던 것 같습니다. 그래서 회의를 하면서 이전 방학식 때 작성했었던 타임라인이 재미있었고 의미있었다는 의견에 따라서 저번 활동보다 재미있는 방향성으로 타임라인을 작성해보고 싶었습니다..!

따라서 취지라고 하면 **유강스 조끼리의 레벨2 학습을 돌아보는 시간을 갖고, 유의미한 시간을 보내기 위함**이 맞을 것 같네요!

++ 꾸밈의 욕구가 많은 사람의 수요도 있었습니다!

> 미션에 대한 간단한 설명

이 부분은 아직 구체화되기 전이라서 다시 회의를 통해서 상세하게 작성을 해야할 것 같습니다. 

일단 간단하게 말씀드려보자면, 타임라인을 피그마를 통해 작성을 하되, 자유로운 양식으로 타임라인을 작성해보는 방향성으로 생각하고 있었습니다. 시상 계획은 잠실 캠퍼스 측에서 따내온 **포비와의 술자리권**을 얻어갈 1팀이 될 것 같습니다. "무조건 상을 받아야지"라는 느낌보다는 타임라인을 회고하는 시간에 의의를 두는 것이 가장 큰 것 같네요!

**[투표 방식]**
투표 방식은 저희가 생각한 바로는 발표를 마치고 구글폼을 통해서 크루끼리 투표를 받아보고 최종 1팀을 선정할 생각이였습니다!

추가적으로 궁금하신 사항 있으면 남겨주세요!! 감사합니다 :)

**Comment by woowahan-leah** [comment]
@Largopie 네네 남겨주신 내용에 대해 충분히 이해했습니다.
위 내용을 바탕으로 구체화해주시고 본문도 업데이트 해주시면 좋을 것 같아요. 🙂

지속적으로 질문 및 답변을 해나가면서 기획을 구체화해주시는 것은 좋은데 구체적인 활동 목적과 타임라인이 그려지지 않는 상황에서는 코치 피드백을 드리기 어렵기도 해서요. (우테코 전체 크루들이 참여하는 행사인 만큼 이러한 요소들이 더욱 중요할 것 같아요) 

이번 활동을 통해 근로 크루들 입장에서도 앞으로 코치에게 어떤 내용을 피드백 받고 싶은 것인지 좀 더 구체화할 수 있었으면 좋겠어요.
미션과 근로 활동을 병행하는 와중에도 고생이 많으신거 너무 잘 알고 있기에 어려움이 있으시다면 언제든 알려주세요.

감사합니다.

**Comment by wmakerjun** [comment]
> 유강스 조끼리의 레벨2 학습을 돌아보는 시간을 갖고, 유의미한 시간을 보내기 위함

유강스 쪼기리 레벨2 학습을 돌아보고 유의미한 시간을 보내기 위한 활동으로 타임라인을 만들어 보는 것이라고 했는데요. 타임라인을 그리면서 회고를 하면서 무슨 이야기를 해야 유용한 시간이 될지, 크루들이 서로 꾸미는 것을 넘어서 어떤 대화를 나눴으면 의미가 있을지를 생각하여 구체적인 설계를 만들어주면 될 것 같아요~! 여러분들이 레벨1 방학식 때 타임라인 그리면서 유의미했던 포인트가 기억나는게 있다면 그런 의도를 작성해줘도 좋을것 같고요 ㅎㅎ

회고가 끝나고 "재밌었다"를 넘어, "이런 이런 이야기를 나눈게 유용했다"란 대화를 나눌 수 있는 상태가 되면 더 좋은 회고가 되겠죠~?

@Largopie

**Comment by solarsalt** [comment]
@Largopie 
안녕하세요 낙타~
방학식 진행 시 요청사항이 있습니다~
아래 사항을 방학식 타임라인에 포함해서 당일에 크루들에게 안내해주세요.
작성해야할 레벨2 설문은 당일(10시)에 코치가 채널로 공지할 예정입니다.

- 방학식 당일은 데일리를 진행하지 않습니다.
- 10시부터 방학식 행사 시작 전까지, 레벨2 설문을 작성해주세요.
