### ISSUE TITLE
[잠실 - 도서 관리] 도서 카테고리 분류를 위한 필요 물품 요청

### ISSUE THREAD

**Issue by dwax1324** [woowacourse/working-scholars#49]
# 개요

도서 분류를 위한 필요 물품을 구매한다.

# 기간
~ 2024.06.05

# 방법
- [x] 북 스탠드 5개 구매
- [ ] 원형 색 스티커 11색 각 2장씩 구매

# 참고 사항
원형 색 스티커 11개 [구매 링크](https://smartstore.naver.com/bepulstore/products/6902260443)
레드, 오렌지, 엘로우, 그린, 라이트블루, 블루, 퍼플, 브라운, 실버, 골드, 블랙 총 11색 각 2장씩
예상 비용 14,200원

**Comment by solarsalt** [comment]
북 스탠드도 구매링크가 있다면, 같이 주시면
스티커와 스탠드 구매 한번에 진행하겠습니다.

스티커는 혹시 모르니 창고에 쓸만한게 있는지 찾아보겠습니다.

**Comment by seokhongkim** [comment]
@dwax1324 북 스탠드는 아래 제품 중 골라주시면 주문하겠습니다.
현재 책장에 있는 스탠드와 같은 사이즈로 골라도 되고, 다른 사이즈가 더 적절하다면 변경해도 괜찮습니다.
이미지에 있는 사이즈 참고하시어 필요한 사이즈 알려주시면 구매하겠습니다.

![Image](https://github.com/woowacourse/working-scholars/assets/44194568/d9ec2060-e579-4dad-929f-f5c0da359dfb)

![Image](https://github.com/woowacourse/working-scholars/assets/44194568/e349b2b2-b212-41cb-afb6-9355e168a1bc)

cc: @solarsalt

**Comment by dwax1324** [comment]
아카데미 북앤드 MB-102 L형 중 2개입[청색] (AR3096) 3개 부탁드립니다!

**Comment by seokhongkim** [comment]
@dwax1324 말씀하신 제품으로 구매 신청했습니다. 배송 오면 공유 드릴게요!

**Comment by seokhongkim** [comment]
스티커 주문 완료했습니다. 배송 오면 공유 드릴게요.

![Image](https://github.com/woowacourse/working-scholars/assets/44194568/653b5ec2-ee20-4177-9d6d-712367477c69)

cc: @solarsalt
