### ISSUE TITLE
[잠실 - 공간] 캠퍼스 비품 관리 프로세스 고안

### ISSUE THREAD

**Issue by jminkkk** [woowacourse/working-scholars#5]
### 개요
캠퍼스 내 비품을 효과적으로 관리하기 위한 프로세스를 고안한다.

### 기간
다음주 금요일 2시까지 회의 및 결과 공유(공간 코어팀에게 전달)

### 방법
논의가 필요한 비품
- 강의실 및 회의실 칠판 지우개, 보드마카, 세제, 핸드워시 상태 확인
  - **"주기적인 비품 상태를 어떻게 관리할 것인가"** 에 대해 논의해주시면 좋을 것 같습니다.
- 케이블 관리 방식
  - 케이블이 제자리에 없는 문제를 어떤 방식으로 해결할지에 대해 논의해주시면 좋을 것 같습니다.
  - 사용 후 제자리에 두라는 공지를 하는 등의 방식을 제안할 수 있을 듯합니다!

그외의 회의자들의 판단하에, 추가적인 비품에 대해서는 선택적으로 프로세스를 논의해도 좋을 것 같습니다.

**Comment by zangsu** [comment]
#10 이슈로 이동되었습니다.
