### ISSUE TITLE
[잠실 - 도서관리] 도서 대여 일지

### ISSUE THREAD

**Issue by zangsu** [woowacourse/working-scholars#55]
# 개요

한정된 도서를 효율적으로 사용하기 위해 도서 대여 일지 비치

# 기간
~ 2024.06.07

# 방법
- 도서 대여 일지 서식 작성
- 도서 대여 일지 출력 및 비치

# 참고 사항

우테코에서는 하루 이상 도서를 대여해 주지 않습니다. 
도서 대여 일지는 선반에 없는 책을 누가 사용중인지 쉽게 파악하기 위한 목적으로 사용할 예정입니다.

[comment - 토미](https://woowacourse.slack.com/archives/C06RGDY21K9/p1716442233460879?thread_ts=1716263651.229659&channel=C06RGDY21K9&message_ts=1716442233.460879)

> - 아래 내용을 고민해 주세요.
>    - 책의 재고를 파악한 후에는 특정 사람이 너무 오래 대여하는 문제는 어떻게 해결 할 수 있을까요?
>    - 현재 책이 책장에 없을때 누구에게 있는지 알 수 있는 최소한의 장치는 어떻게 만들 수 있을까요? (최소 방학식 같은 날은 현재 책 대여자들에게 책장두고 가달라고 안내 할수있어야 관리가 가능한 상태라고 생각합니다.)

**Comment by ehtjsv2** [comment]
### 검토마감기한
~6월10일(월) 18:-00

### 도서대여일지에 들어가야 하는 것(최소한의 장치)
* 대여날짜(월/일)
* 닉네임
* 책이름
* 반납 여부

### 필요한 것 
볼펜 1개, 대여일지 20장출력, 클립보드

### 도서대여일지 사용방법
1. 도서 선반을 벗어나 책을 들고가는 경우에만 도서대여일지 작성
2. 반납할 때, 반납여부 체크
3. 도서대여일지는 클립보드에 끼워 볼펜과 함께 가운데 선반에 위치시킨다.

### 도서대여일지 PDF
https://drive.google.com/file/d/17WUH19fS-XnqNUCQ1UJUA6xtRBHxVuyx/view?usp=sharing

**Comment by solarsalt** [comment]
- 그동안 어떤 장치없이 도서를 관리했으니, 최소한의 장치로 이번 시도를 해보는 것은 좋을 것 같아요!
- 실행해보고 긍정적인 효과가 있다면, 선릉에도 시도와 결과를 공유해주셔도 좋겠네요~
