### ISSUE TITLE
[선릉 - 우주먼지 팀]  6월 3째 주 비품 현황

### ISSUE THREAD

**Issue by gaeun5744** [woowacourse/working-scholars#63]
## 검토 마감 기한

~ 2024.6.12

** 코치님들의 피드백을 반영해 근로 인수인계 문서에 업데이트를 하면 좋을 것 같아서, 12일까지 요청 드립니다!

### 부족한 재고 체크
    - 검정 보드마카(DONG-A) : 2개
    - 검정 네임펜 : 8개
    - 화이트보드 지우개 : 3개
    - 물티슈 : 0개
    - 배수구 클리너 : 8개
    - 보드마카 세트(Staedtler) : 1세트

### 비품 관리 스프레드 시트

- https://docs.google.com/spreadsheets/d/1km7F7B-eAfxM38jt6A9UT8JUK9vlBdVe53w3ct1QDTg/edit#gid=898395765

새로 작성한 비품 관리 시트입니다! 혹시 추가로 파악하면 좋은 비품 등에 대해 피드백을 주시면 감사하겠습니다!

### 문의 사항

- 배수구 클리너, 청소기 헤드처럼 크루들이 사용하지 않는 비품들도 재고를 파악하여 알려드리면 좋을지 궁금합니다!

- 포스트잇, 청소기 필터처럼 재고가 충분한 물품에 대해서도 항상 재고를 체크하면 좋을지 궁금합니다!

**Comment by wmakerjun** [comment]
@gaeun5744 
> 배수구 클리너, 청소기 헤드처럼 크루들이 사용하지 않는 비품들도 재고를 파악하여 알려드리면 좋을지 궁금합니다!

=> 크루들이 직접 사용하지 않는 비품은 재고 파악하지 않아도 괜찮습니다 :)

> 포스트잇, 청소기 필터처럼 재고가 충분한 물품에 대해서도 항상 재고를 체크하면 좋을지 궁금합니다!

=> 오 좋은 질문인것 같아요. 재고가 충분한 물품에 대해서는 체크를 굳이 안해도 될 것 같긴한데요. 재고 '수량'까지는 체크하지 않아도, 대략적으로 '충분해 보임' 정도의 상태로 관리하는건 어떨까요~? 아예 제외하면 나중에 혼돈이 올 것 같기도 해서요 ㅎㅎ
