### ISSUE TITLE
[선릉 - 게시판] 우아한 게시판 프로젝트 제안서 (update. 0510)

### ISSUE THREAD

**Issue by vi-wolhwa** [woowacourse/working-scholars#7]
## 1. 서론
- **목적**
선릉 캠퍼스 및 코치와의 원활한 소통을 위해 우테코 내 문의 게시판 구축의 필요성을 인지한다. 이는 크루와 크루 그리고 크루와 코치 사이의 커뮤니케이션을 강화하고, 우테코 커뮤니티 내에서 발생하는 다양한 이슈를 효과적으로 해결하기 위함이다.

## 2. 운영 계획
- **오프라인 문의**
    - 문의 내용을 포스트잇에 적어 지정된 바구니에 넣는다.
- **온라인 문의**
    - 게시판 옆 QR코드를 스캔해 구글폼을 통해 문의 내용을 제출한다.
- **응답 메커니즘**
    - 게시판 TF팀은 수집된 문의를 검토하고 결과를 게시판을 통해 공유한다.
- **대나무숲 기능**
    - 근로가 계획하는 행사, 크루들의 생일 혹은 TMI 등을 가볍게 공유할 수 있는 공간으로 활용한다.

## 3. 실행 예시
- 현재 접수된 문의사항 N개, 해결된 문의사항 N개
- 진행 중: A 문의를 B 방법으로 해결할 예정이다.
- 처리 완료: A 문의를 B 방법으로 해결했다.
- 처리 불가: A 문의를 B 방법으로 해결하려 했으나, C의 이유로 불가능하다.

## 4. 실행 계획
- 프로젝트에 대한 승인 후 필요 공간/물품을 준비 예정

## 5. 코치에게 문의사항
- **공간 사용 여부에 대한 문의**
    - 게시판 및 문의함으로 사용하고 싶은 공간에 대한 사진 첨부
- **필요 물품 요청**
    - 전지 사이즈의 포스트잇
    - 문의함으로 사용할 포스트잇 및 바구니(사물함 사용이 불가능할 경우)
- **구글폼 계정에 대한 문의**
    - 온라인으로 문의받기 위한 구글폼 사용과 관련하여, 우테코에서 제공하는 계정을 사용하는 것이 좋은지, 아니면 게시판 TF팀의 계정으로 구글폼을 만들어 운영하는 것이 좋은지에 대한 의견 요청

**Comment by imakerjun** [comment]
월하~ 좋은 제안줘서 고마워요~!
'목적' 부분에도 공감이 가고, 이 활동을 통해 크루들이 커뮤니티 속에서 일어나는 다양한 이슈들을 잘 이야기했으면 하는 바램입니다! ㅎㅎ
그래서 딱 1가지 제안을 한다면, 운영 계획이 4개가 있는데요. 저걸 동시에 하는 것도 좋지만, 크루들이 의견을 내는데 가장 쉽고 유용할 것 같다 싶은거를 하나씩 시도해보면 어떨까 싶어요~ 처음부터 4개를 동시에하면 보통, 이거는 어디에다 작성해야할까? 하다가 '에잇 모르겠다!' 하고 의견 제시를 못하는 경우가 생기더라구요 ㅎㅎ

그래서 크루들이 가장 많이 사용할 것 같은걸로 하나씩 시도해보고, 거기서 많이 이루어진다면 굳이 다른건 운영하지 않아도 될 것 같아요~!
하나씩 스텝 바이 스텝으로 시도해보면 더욱 좋을것 같아요~!

**Comment by Largopie** [comment]
## 5. 코치에게 문의사항

추가적으로 문의사항에 대한 답변은 아직 받지 못한 것 같습니다!
위에 문의사항에 대한 답변도 추가적으로 받을 수 있을까요?

**Comment by wmakerjun** [comment]
## 5. 코치에게 문의사항
 **공간 사용 여부에 대한 문의**
    - 게시판 및 문의함으로 사용하고 싶은 공간에 대한 사진 첨부 
 **필요 물품 요청**
    - 전지 사이즈의 포스트잇
    - 문의함으로 사용할 포스트잇 및 바구니(사물함 사용이 불가능할 경우)
  **구글폼 계정에 대한 문의**
    - 온라인으로 문의받기 위한 구글폼 사용과 관련하여, 우테코에서 제공하는 계정을 사용하는 것이 좋은지, 아니면 게시판 TF팀의 계정으로 구글폼을 만들어 운영하는 것이 좋은지에 대한 의견 요청
    

# 의견
- 문의 해준 내용을 토대로 봤을 때 온라인으로 먼저 시도해보고 실제 공간 사용 및 물품을 이용해보면 좋을것 같아요~!
- 공간 사용을 병행하고 싶다면 포스트잇과 이를 담을 수 있는 간단한 바구니는 제공 가능합니다. 하지만 전지 사이즈의 포스트잇은 제품이 비싼편이기 때문에, A3용지나 A4용지를 활용해보면 좋을것 같아요~!
- 우테코 공간의 일부를 미리 '공유'하고 사용해보는것도 괜찮은 것 같아요 😄

**Comment by woowahan-leah** [comment]
## 추가 의견

- A4용지를 통해 프린터를 활용해야 한다면 코치에게 사전에 문의주세요! 소통은 슬랙 근로 채널로 부탁드립니다 🙂

**Comment by 00kang** [comment]
게시판 운영 방식 재선정으로 인한 혼선을 방지하기 위해 close합니다!
