### ISSUE TITLE
[포수타] 선릉 노트북 줌 권한 관련 문의

### ISSUE THREAD

**Issue by nak-honest** [woowacourse/working-scholars#75]
# 개요
포수타 팀원 2명 전부 선릉 캠퍼스로 배정이 되어, 포수타 진행 시 잠실 노트북을 사용할 수 없는 상황입니다.
선릉 노트북으로 포수타 줌을 시작할 수 있는지 여쭈어 봅니다.

# 기간
~ 2024.07.09 18:00

# 방법
- 선릉 캠퍼스의 노트북으로 포수타 줌을 시작할 수 있다면 해당 노트북으로 시작한다.
- 선릉 캠퍼스의 노트북으로 포수타 줌을 시작할 수 없다면 이전 포수타 팀원이 줌 권한을 부여해준다.

**Comment by seokhongkim** [comment]
@nak-honest 낙낙 안녕하세요.
선릉 캠퍼스의 노트북으로 포수타 줌 진행하셔도 괜찮습니다.

선릉 캠퍼스 노트북으로 포수타 진행하는 방법도 포수타 진행 가이드에 업데이트 부탁드려요. 🙂
