### ISSUE TITLE
[잠실 - 코어팀] 인수인계 문서 확인 공지

### ISSUE THREAD

**Issue by J-I-H-O** [woowacourse/working-scholars#76]
# 개요
- 각 팀에 인수인계 문서를 확인할 것을 공지한다.

# 기간
~ 2024.07.19

# 방법
- [x] 구글 드라이브 링크 전달

# 참고 사항
[구글 드라이브 링크](https://drive.google.com/drive/folders/1UxskWtr6vOWo1I5D0DKxt0RGPBCAHjsE)

**Comment by jongmee** [comment]
### 공지할 내용 추가
- 다음주 금요일 단체 회의에서 각 팀의 업무 공유 시간을 가진다.
    - [한 주동안 필수로 해야 할 일] 각 팀이 어떻게 업무를 진행할지 정한다.
- 회의할 때마다 회의록을 남기고, 근로 조직도 스프레드 시트에 업무 내용을 매주 기록해야한다.
- 이슈 발행과 코치 확인은 각 팀에서 진행한다.
