### ISSUE TITLE
[잠실 - 캠퍼스 관리] 공용 우산 생성 건의

### ISSUE THREAD

**Issue by Hain-tain** [woowacourse/working-scholars#77]
# 개요
- 잠실 캠퍼스 우산꽂이함의 자리가 부족하여, 비가 오는 날에 우산이 잘 정리되지 않는 경우가 많다.
(3단 우산 등 길이가 짧은 우산의 경우 우산 꽂이함에 넣을 수 없다.)
- 캠퍼스 내에 주인 없는 우산들이 많아보이나, 개인이 가져온 우산들과 잘 구분이 되지 않는다.

- 우산 꽂이함이 더 있으면 좋을 것 같다.
- 주인이 없는 우산들을 공용 우산으로 사용하여, 유휴 자원을 잘 활용하면 좋을 것 같다.

# 요청
- 공용 우산 꽂이함으로 사용할 우산 꽂이함 2개 추가 구매 요청드립니다.
- (현재 있는 우산 꽂이함으로는 개인 우산과 공용 우산을 모두 수용하기 어렵습니다.) 

# 기간
~ 2024.07.26.

# 방법
- [ ] 공용 우산 꽂이함과 개인 우산 꽂이함을 구분할 수 있도록 각 우산 꽂이에 표시를 해준다.
- [ ] 잠실 크루들에게 공용 우산 꽂이함이 아닌 개인 우산 꽂이함으로 우산을 옮길 수 있도록 공지한다.
- [ ] 남은 우산들은 공용 우산으로 간주하고, 각 우산의 손잡이 부분에 `public` 라벨링 작업을 한다.
- [ ] 잠실 크루들에게 공용 우산에 대해 공지한다.
- [ ] 공용 우산 관리에 대해서는 개인의 양심을 믿고 자율로 이용하고 반납하도록 한다. 그러나 관리가 잘 되지 않는다고 판단 될 경우 대여/반납 기록을 남기도록 한다.

# 참고 사항

- [잠실 우산 현황]
<img width="671" alt="image" src="https://github.com/user-attachments/assets/967115c5-07ea-4845-a778-67a431414681">

- [선릉 공용우산 관련 이슈](https://github.com/woowacourse/working-scholars/issues/15)

- 선릉캠 공용 우산 꽂이함
<img width="684" alt="스크린샷 2024-07-19 오전 10 45 12" src="https://github.com/user-attachments/assets/c34dafb8-cc78-4c3a-97fc-33cbd5fbb16b">

- 선릉 채널 공용 우산 관련 공지
<img width="980" alt="스크린샷 2024-07-19 오전 10 40 39" src="https://github.com/user-attachments/assets/c863c79e-88f6-475e-8f4d-74a3d1548fa7">

**Comment by sh1mj1** [comment]
굳굳!! 오늘 이야기 하러 가려고했는데 고생했습니다.!!!!

우산들이 제대로 남아 있는지 정기적으로 확인하는 요일이 필요할까요?

**Comment by Hain-tain** [comment]
1. 저희 매주 화요일마다 회의가 있으니까, 매주 화요일에 가볍게 살펴보면 좋을 것 같습니다.
2. Assigner 변경 완료했습니다! 👍

**Comment by sh1mj1** [comment]
문제 없는 것 같아요!
주인이 없는 우산을 어떻게 파악해야 할지 이야기를 해봐야겠군요!
수고하셨습니다 감사합니다

**Comment by Wonmi91** [comment]
우산 정리가 늘 고민이었는데, 공용 우산과 개인 우산 구분해 두는 것 아주 좋습니다.
잠실 캠퍼스 내에서 적절하게 배치할 공간을 탐색하신 후, 크기가 적정한 우산꽂이를 선택해 구매 링크 남겨주시면 구매 도와드릴게요 : )
(공간을 많이 차지하지 않도록 고려해주세요.)

만약 라벨링을 위한 프린트가 필요하다면, 근로 채널에 코치 멘션해서 요청해주세요. 🙂
