### ISSUE TITLE
[선릉 - 만능팀] 선릉캠퍼스 설문

### ISSUE THREAD

**Issue by pricelees** [woowacourse/working-scholars#79]
## 개요
- 선릉캠퍼스의 새로운 업무 기획을 위해 크루를 대상으로 설문을 진행합니다.

## 내용
- **현재 불편함을 느끼는 점**과 **새로 시도해보고 싶은 일**에 대해 설문을 진행합니다.
- 설문 방식
   -  1안 : 구글폼을 이용한다.
   -  2안 : 무중력 광장에 있는 칠판과 포스트잇을 이용한다.

## 기타
- 설문 내용과 기타 자세한 사항은 설문 방식이 정해진 이후에 진행합니다.

## 검토 기한
- 7월 24일(수) 오후 12시

## 마감 기한
- 7월 26일(금) 18시

**Comment by pricelees** [comment]
@seokhongkim @solarsalt 

### 진행 방식
- **구글폼**을 이용하여 설문을 진행합니다. 
- 링크: [선릉 캠퍼스 수요 조사](https://docs.google.com/forms/d/e/1FAIpQLSd3t4yjSLVRGMH01rTgsVigNbl0wukYCm1XRukGatwP4VKilg/viewform)

### 결정 배경
- 칠판을 고려했던 것은 **접근성이 좋고 눈에 띈다는 장점** 때문이었으나, 여러 아이디어를 모아야 하는 현 상황에서는 **예시를 들어 설문을 진행**하는 것이 좋다는 생각 하에 구글폼으로 진행하도록 결정하였습니다.

- 설문에서 사용하는 예시는 레벨2에서 잠실 근로 크루들을 대상으로 **하고 싶은 업무**에 대해 조사했던 것을 사용합니다. 

### 설문 내용
- **만능팀에서 나온 몇몇 아이디어에 대한 필요성** 조사(분실물 채널 생성 및 매뉴얼 관리, 마지막 퇴실자가 직접 체크하며 확인할 수 있는 체크리스트 작성 등)
- **현재 선릉캠퍼스 생활에서 느껴지는 불편함**에 대한 조사
- **근로에서 새롭게 해줬으면 하는 업무**에 대한 조사

### 일정
- **8월 2일(금) 오후 12시**까지 설문을 진행하고 결과에 대해선 추가적으로 공유 드리겠습니다.

**Comment by pricelees** [comment]
@seokhongkim @solarsalt 

7월 30일부터 8월 2일까지 [링크](https://docs.google.com/forms/d/e/1FAIpQLSd3t4yjSLVRGMH01rTgsVigNbl0wukYCm1XRukGatwP4VKilg/viewform)에 있는 설문을 진행 했고, 불편사항이나 새로운 이벤트에 대한 내용 취합 및 진행 방식 결정 후 몇가지 업무에 대한 제안을 드립니다. 4가지 안건에 대해 검토 후 피드백 주시면 감사하겠습니다.  

# 안건

### 전체 일정

- 검토는 가능하시다면 **8월 6일(화) 18시**까지 부탁드립니다.
- 업무는 검토 후 별도로 이슈를 생성하여 진행할 예정입니다.

<br>

### 분실물 채널 생성 및 가이드라인 제시

**배경**

- 현재 분실물 관련 글은 **캠퍼스-선릉** 채널에 올라오고 있으나, 다른 글에 섞여 분실한 사람과 습득한 사람 모두 파악하기 힘든 문제가 있습니다.
- 그래서 별도의 항목으로 필요 / 불필요 설문을 진행했고, 전체 응답자 중 75%가 필요하다는 응답을 했습니다.

**진행 방식**

- 만능팀 3명(상돌, 안나, 테니)가 진행합니다.
- 별도의 슬랙 채널을 만들고, 글 작성 템플릿과 가이드라인을 제시합니다.
- 분실물은 캠퍼스 내에 미사용 사물함 등 별도의 공간에 보관할 예정입니다.
- “**분실물을 발견해서 글을 올린 사람에게 칭찬과 박수와 같은 사소하더라도 기분 좋은 선물이 있으면 좋겠어요**”와 같은 설문 응답에 대한 조치 방법도 고려중입니다.

**기대 효과**

- 별도의 분실물 보관 공간이 생기기에, 특정 인원과 일정을 맞추지 않아도 될 것이라고 생각합니다.
- 분실물 파악이 이전보다 수월해질 것으로 기대합니다.

<br>


### 입실 / 퇴실 체크리스트

**배경**

- [링크](https://woowacourse.slack.com/archives/C06JUSAEM7B/p1721780912486889)에 나온 것 처럼, 해야 할 업무라는 것은 알지만 가끔씩 놓치는 경우가 있습니다.
- 퇴실 하는 사람만 하니까 처음 하는 경우 어떤 일을 해야 하는지 잘 모르는 사람이 많다는 문제점이 있었습니다.
- 냉장고 옆과 문 밖에 체크리스트가 붙어있지만 인지를 못하는 크루들이 많다는 것을 파악했습니다.
- 그래서 별도의 항목으로 필요 / 불필요 설문을 진행했고, 전체 응답자 중 75%가 필요하다는 응답을 했습니다.

**진행 방식**

- 만능팀 2명(다르, 초코)가 진행합니다.
- 슬랙 왔다감 채널에 템플릿을 만드는 것을 우선으로 하고, 이 과정에서 문제가 있는 경우 코팅지 등을 활용하여 수기로 체크할 수 있는 체크리스트를 만들 예정입니다.
- 마지막 퇴실 시 **무조건 작성**해야하는 왔다감 채널에 체크리스트 템플릿을 마련할 예정입니다.

**기대 효과** 

- 추가적인 업무인 만큼 어느정도 거부감이 들 것이라고 예상됩니다. 그러나 퇴실 체크리스트가 잘 지켜지지 않는 문제가 종종 발생하고 있으므로, 수기로 체크하는 것으로 리마인드를 하게 되면 이러한 문제를 방지할 수 있을 것입니다.

<br>


### 화이트보드

**배경**

- 팀플하다가 화이트보드를 쓸 일이 자주 있는데, 현재 화이트보드의 개수가 너무 적어서 불편하다는 설문 응답이 있었습니다.

**진행 방식**

- 팀 당 하나의 작은 화이트보드를 지급합니다.
- 혹은 잠실 캠퍼스에서 진행 중인 방식처럼 두 팀 당 하나의 큰 화이트보드를 마련하여 양면을 사용할 수 있도록 합니다.

**기대 효과** 

- 팀 내에서 그림을 그리며 논의를 해야하는 등의 경우에서 유용하게 사용할 수 있습니다.

<br>


### 싱크 선반

**배경**

- 텀블러 등의 설거지를 한 후 선반에 두어 말리는 공간이 필요하다는 설문 응답이 있었습니다.

**진행 방식**

- 싱크 선반을 한 개 구매하여 싱크대 옆에 둡니다.

**기대 효과** 

- 물기가 묻은 용기를 선반에서 말린 후 들고 다니거나, 자신의 자리에 들고가서 말리는 등의 불편함을 해소할 수 있습니다.

# 기타

- `개발 이야기가 아닌, 사람 이야기를 할 수 있는 토크쇼 개최했으면 좋겠어요. (유연한 수다 타임 / 백엔드 살롱 과 비슷하게)`
- `캠퍼스에 항상 틀어두는 잔잔한 bgm을, 아침에만 신나는 케이팝으로 바꿨으면 좋겠습니다. 아침마다 조금이나마 힘이 날 수 있을 것 같아요.`
- 새로운 이벤트에 대한 위와 같은 설문 응답이 있었습니다. 해당 부분은 위 이슈를 처리한 후 별도로 제안 드려 승인 후 진행할 예정입니다.

**Comment by seokhongkim** [comment]
@pricelees 내용 확인과 회신이 늦었네요. 😢 
내용을 잘 정리해주셨고, 해결해보려는 방법이 너무 복잡하거나 비용이 크지 않다고 판단하여 가급적 진행하는 방향으로 의견을 모았습니다.

**분실물 채널 생성 및 가이드라인 제시**
- 빠른 시도 후 계속 보완해보세요.

**입실 / 퇴실 체크리스트**
- 위와 같은 의견입니다.

**화이트보드**
- 구매하려는 제품의 링크와 개수, 금액을 알려주시면 추가로 검토해보겠습니다.
- [종이 형태의 이젤패드](https://www.coupang.com/vp/products/1276358319?itemId=22435052134&vendorItemId=89479625109&src=1042503&spec=10304025&addtag=400&ctag=1276358319&lptag=10304025I22435052134V89479625109&itime=20240808163006&pageType=PRODUCT&pageValue=1276358319&wPcid=17231017757899572754114&wRef=&wTime=20240808163006&redirect=landing&gclid=CjwKCAjw2dG1BhB4EiwA998cqKRHzEHd8-n3nMcqKkJMKXYdDzgczW9aCVTgj1jkHyx_mtw1pR6xUhoCKvwQAvD_BwE&mcid=e1baf9b5294548ffaabe75df3e6589fa&campaignid=21519412236&adgroupid=)도 있으니 화이트보드와 비교해 어떤 것이 더 필요할 지 확인해보세요.

**싱크 선반**
- 싱크대 크기와 비치할 공간을 정확히 확인하시고, 적절한 상품 링크를 전달주세요. 구매하려는 제품의 링크와 금액을 알려주시면 추가로 검토해보겠습니다.
- 선반이 아니라 [간단한 접이식 형태](https://www.coupang.com/vp/products/6225969471?itemId=12485379018&vendorItemId=78767791861&src=1042503&spec=10304025&addtag=400&ctag=6225969471&lptag=10304025I12485379018V78767791861&itime=20240808162447&pageType=PRODUCT&pageValue=6225969471&wPcid=17231017757899572754114&wRef=&wTime=20240808162447&redirect=landing&gclid=CjwKCAjw2dG1BhB4EiwA998cqPYcRqpvZTOnmYLPlF4-qCOR-GIIZJBLllJwnb_-qWLX3gtRpSPm3xoCNFMQAvD_BwE&mcid=7d6edb2e701a45a3aa8835206cc8806c&campaignid=21307631972&adgroupid=)도 있습니다. 참고해보세요.
- 싱크 선반에 건조대를 비치했을 때 물이 상판 위에 흐르는 경우 누전의 위험이 있습니다. 물이 싱크대로 잘 흐를 수 있는 제품인지 확인해 주세요.

추가로, 설문 폼은 근로 장학생 채널에 공유해드린 구글 드라이브로 이동해 주세요.
전체 응답자 중 75%라고 공유해주실 때, 전체 응답자가 몇 명인지도 공유해 주시면 좋겠습니다. (4명의 응답자 중 3명이 동의한 것과, 80명의 응답자 중 60명이 동의한 것은 같은 동의율이라도 응답률이 다르므로, 다르게 접근해야 한다고 생각합니다.)

cc: @solarsalt

**Comment by solarsalt** [comment]
> 캠퍼스에 항상 틀어두는 잔잔한 bgm을, 아침에만 신나는 케이팝으로 바꿨으면 좋겠습니다. 아침마다 조금이나마 힘이 날 수 있을 것 같아요.

@pricelees 
위 내용 검토하시기 전 사전 정보 공유드려요.
잠실캠퍼스, 선릉캠퍼스 모두 bgm이 항상 나오는데, 우아한형제들 사내용어로는 '배려의 비트'라고 부르고 있습니다.
사내 모든 공간의 bgm은 특별한 이유없이는 선곡을 바꾸거나 볼륨을 조정하지 않는 방향으로 관리되고 있습니다.
(e.g. 볼륨을 조정해야할때는, 관련팀에 사전에 공유하고 허락을 받고있어요~)
또 선릉캠퍼스는 bgm재생만을 위한 폰을 회사에서 대여해 사용중인 것으로 알고 있어요. 

정리하자면
- 일단은 선릉 캠퍼스(=테크살롱)도 우형 사내 공간 중 하나로서 특별한 사유가 아니면 bgm을 조정하지 않아야 할 것 같습니다.
- 만약 그래도 실행하신다면, bgm재생을 위한 기기를 특정시간만 개인 기기로 대체해 재생하는 방법이 있겠습니다.
