### ISSUE TITLE
[잠실 - 문제해결] 우산 꽂이함 구매

### ISSUE THREAD

**Issue by vi-wolhwa** [woowacourse/working-scholars#83]
# 개요
- 단우산을 관리하기 위한 우산꽂이함을 찾는다.
- 공간을 많이 차지하지 않아야 한다.

# 기간
~ 2024~07~30

# 방법 및 결과
- 용도에 맞는 우산꽂이 검색 및 선택
- [구매링크](https://link.coupang.com/a/bLF7eM)

@Wonmi91

**Comment by 3Juhwan** [comment]
더이상 유효하지 않은 이슈로 닫습니다.
