### ISSUE TITLE
[잠실 - 문제해결] 크루 민원 창구

### ISSUE THREAD

**Issue by vi-wolhwa** [woowacourse/working-scholars#85]
# 개요
- `잠실-캠퍼스` 채널에서 민원을 편하게 말하기 어려움이 있다.
- 익명으로 자유롭게 민원을 제출하기 위한 창구가 필요하다.

# 기간
~ 2024.08.02

# 방법
- [x] 민원 발행 구글 폼 생성
- [ ] 민원 발행 방식 공지

**Comment by 3Juhwan** [comment]
안녕하세요. 망쵸입니다. :) 
구글폼을 생성했습니다. 임의로 작성한 내용이 어떤지 검토 부탁드립니다! 
링크는 근로 공유 폴더에 생성했고 [여기](https://docs.google.com/forms/d/1vVwuNDp0QAU8IXwbbSDNerrFUZTXLHSFrKcaajc7qMc/viewform?edit_requested=true)에서 확인할 수 있습니다.
