### ISSUE TITLE
[잠실 - 만능팀] 옹기종기 라이트닝 토크 기획

### ISSUE THREAD

**Issue by healim01** [woowacourse/working-scholars#86]
# 개요
크루들이 작은 주제에 대해서 가볍게 이야기할 수 있는 자리를 마련하기 위한 기획 

옹기종기 라이트닝 토크 (옹라토) 기획 구체화

# 기간
~ 2024.08.01

# 방법
- 자세한 사항은 회의록 내부에 작성했습니다. 
- [07/30 회의록](https://github.com/woowacourse/working-scholars/wiki/7.30-%28%ED%99%94%29-%EC%9E%A0%EC%8B%A4-%EB%A7%8C%EB%8A%A5%ED%8C%80-%ED%9A%8C%EC%9D%98%EB%A1%9D)

# 참고 사항

**Comment by woowahan-leah** [comment]
@healim01 빠른 시간 내에 이렇게 구체화 하시느라 고생하셨습니다! 🙂 

지금 작성하신 대로 진행해주시면 될 것 같아요~ 
어떤 행사던 정기적으로 운영하다 보면 중간중간 개선이 필요할 수도 있는데요, 필요한 게 있으시면 슬랙 근로 채널을 통해 알려주세요.

여러분들이 주도하시는 행사가 긍정적인 경험으로 이어지길 바랄게요 ㅎㅎ

**Comment by healim01** [comment]
넵! 감사합니다~! 
진행 후 중간 상황 전달드리도록 하겠습니다~!

**Comment by Wonmi91** [comment]
@healim01 
추가로 다과 구매가 필요하다면 미리 요청주시면 구매 도와드리겠습니다. 구매 링크를 함께 전달주세요!
가볍게 토크하는 자리인만큼, 간단한 다과로 충분할듯 합니다 : )

**Comment by healim01** [comment]
@Wonmi91 @woowahan-leah 

추천 받은 주제들 중 이번 주 주제 선정해서 컨펌 이후 발표자를 모집할거 같습니다!! 
선정된 주제 한번 확인 부탁드려요~!! 

선정된 토크 주제 : **우리 팀 기능 구현 자랑**

그리고 자세한 사항 및 다과 관련해서는 회의록에 작성해놨습니다!
감사합니당

[8월7일 라이트닝 토크 회의](https://github.com/woowacourse/working-scholars/wiki/8.2-%28%EA%B8%88%29-%EC%9E%A0%EC%8B%A4-%EB%A7%8C%EB%8A%A5%ED%8C%80-%ED%9A%8C%EC%9D%98%EB%A1%9D)

**Comment by woowahan-leah** [comment]
@healim01 네 지금 기획하고 계신대로 진행하셔도 무방합니다!
링크해주신 다과는 제가 잠실 캠퍼스로 주문해둘게요! (배송 완료되면 알려드리겠습니다 🙂 )

참고로 앞으로의 라이트닝 토크 주제 선정하실 때 다른 컨퍼런스나 행사에서 어떤 식으로 라이트닝 토크를 운영했는지 참고해보셔도 좋을 것 같아요~
아래는 작년 5기 최종 데모데이 행사에서 크루(+ 일부 코치)들이 제출한 주제인데요, 어떤 주제가 크루들의 관심을 끌 수 있을지 참고 목적으로 활용하실 수 있을 것 같아 첨부합니다 ☺️ 
|A|B|
|---|---|
|![image](https://github.com/user-attachments/assets/606f8068-8025-4f7e-86c4-daf6105096c8)|![image](https://github.com/user-attachments/assets/90a16f88-f8c8-4b64-aa25-06f33754b101)|

**Comment by woowahan-leah** [comment]
또 이번에 운영 해보시고 다과 부족하진 않았는지도 알려주세용 ㅋㅋㅋㅋ

**Comment by tkdgur0906** [comment]
@Wonmi91 @woowahan-leah 
안녕하세요! 워니,레아
다름이 아니라 내일 진행될 예정이었던 첫 옹라토에 대해 긴급한 회의가 있어 회의 진행사항 전달드립니다.
내일로 예정되었던 옹라토가 시간부족 및 홍보 부족으로 인해 당장 진행하기에 원활하지 않은 퀄리티라고 판단을 했습니다.
이에 대해, 근로팀 회의 중에 조금 더 보충을 한 뒤 다음주에 진행하는 것에 대한 의견이 나와서 전달드립니다!
다음주에 진행하게 된다면 좀 더 자세한 기획 및 원활한 발표자 모집이 가능할 것 같은데, 다음주에 시작하는 것에 대해 어떻게 생각하시는지 궁금합니다!
만약 이번주에 진행해야 한다면 발표자 없이 수다 타임으로 진행해야할 것 같습니다!

**Comment by Wonmi91** [comment]
@tkdgur0906 

만나서 말씀드린것처럼, 1주 미루는 것 괜찮습니다 : )
더불어 하나의 주제로 한정 지어 진행하는 것도 좋지만, 여러 주제+발표자 모집을 해보시고 한 사람당 짧은 시간동안 발표하는 형식으로 진행해보는 것도 좋을 것 같아요! (이미 주제를 제안한 크루들도 있으니..!)
크루들이 라이트닝 토크에 관심을 갖게할 방법도 고민해보셔도 좋을 것 같고요~
카피, 헤일리가 편하신 방식으로 한번 더 논의해보시고, 결정되시면 말씀주세요!

**Comment by pakxe** [comment]
제 1회 옹라토 진행 완료로 이슈 닫겠습니다!
