### ISSUE TITLE
론칭 페스티벌 행사 지원

### ISSUE THREAD

**Issue by leftykhim** [woowacourse/working-scholars#87]
# 요청 업무

## 개요
- 8월 23일(금)에 진행할 론칭 페스티벌의 일부 프로그램을 기획하고 전체 행사 진행을 지원한다.
  - 론칭 페스티벌: 서로의 서비스를 소개하고 함께 칭찬하고 격려할 수 있게 하는 행사 (4차 데모데이)

## 근로 필요 기간
- 8월 9일(금)~23일(금) 2주

## 론칭 페스티벌 타임 테이블
- 10:00 ~ 11:00 사전 행사
- 11:00 ~ 11:30 자리 배치
- 11:30 ~ 13:00 점심 식사
- 13:00 ~ 14:00 데모시연
- 14:00 ~ 16:00 부스 운영
- 16:00 ~ 16:30 뒷 정리

## 필요한 업무 (겸업 가능)
- 론칭 페스티벌 오전 프로그램 기획 및 진행: 당일 오전 10시부터 11시까지 론칭 페스티벌에 어울리는 사전 행사 진행
- 부스 운영을 위한 자리 배치 및 복구: 정해진 자리에 맞춰 실제 배치 및 복구 (가장 큰 강의장)
- 데모시연 시간 진행자(MC): 오후 데모시연 시간 진행
- 간식 구매: 캠퍼스별 30만원씩 간식 구매
- 코치와 직접 소통할 대표 크루 (당일 총괄 운영까지 담당)
- 당일 각종 진행 지원

## 필요 인원
- 여러분이 정해주세요.

## 참고사항
- 론칭 페스티벌은 각 캠퍼스에서 오프라인으로 따로 진행합니다.
- 근로 가능 인원 먼저 전달해 주면 좋겠습니다. 코치와 직접 소통할 대표도 각 캠퍼스별로 한 명씩 선정해 주세요.
- 인원이 결정되면 오전 프로그램 아이디어 몇 개를 며칠 내로 우선 전달해 주세요. 본격적인 기획은 코치 승인 후 진행하면 됩니다.
- 부스 자리배치도는 코치들이 제공할 예정입니다.
- 데모시연은 팀당 5분입니다. 전체 데모를 1시간 내로 끝내주세요.
- 간식은 구매 링크를 코치에게 전달하면 됩니다.
- 론칭 페스티벌에 대한 문의는 왼손과 구구에게 해주세요.

**Comment by zangsu** [comment]
잠실 캠퍼스 : 기획 근로 (종이, 해시, 짱수, 몰리) 담당으로 배정하겠습니다!
8/13(화) 회의때 오전 프로그램 관련 회의 진행 후 아이디어 전달 드리겠습니다!
