### ISSUE TITLE
[선릉] 비품 관리 고안

### ISSUE THREAD

**Issue by gaeun5744** [woowacourse/working-scholars#9]
### 개요
- 선릉 캠퍼스 비품 관리 방법 고안
-  현재 비품 관리는 누가 재고를, 얼마나 가져가는지에 대한 파악이 불분명하고 제대로 정리되어 있지 않음

### 목적

해당 시트를 통해 코치님들이 부족한 재고를 쉽게 파악해서 보충할 수 있게 하는 것이 목적

### 운영 계획

크루들이 밑의 정보를 구글폼에 입력하고 비품을 가져갈 수 있도록 한다.
- 닉네임
- 비품(예시: 휴지)
- 필요한 곳(예시: 여자화장실)

이를 엑셀로 정리한 비품 관리 시트를 일정 기간마다(혹은 실시간으로) 코치님들에게 전달

### 문의 사항

- 해당 건에 대한 코치님들의 피드백
- 코치님들이 해당 비품 관리 시트를 통해 파악하는 것이 편하실지, 아니면 다른 구글폼을 만들어서 크루들로부터 부족한 재고 요청을 따로 받는게 더 편하실지 궁금합니다

**Comment by woowahan-leah** [comment]
@gaeun5744 
## 코치 답변
### 해당 건에 대한 피드백
비품 관리 방법에 대한 고민을 잘 정리해주셨네요!
누가 재고를 얼마나 가져가는지에 대한 파악이 불분명하고 제대로 정리되어 있지 않은 문제를 해결해볼 수 있을 것 같아요.

다만, 코치가 따로 비품을 추가로 주문하여 재고를 채워둘 때 재고 현황 업데이트를 어떻게 할 수 있을지도 고민해봐주실 수 있을까요?
이를테면 다음과 같이 추가된 재고에 대하여 근로 크루들에게 안내드리면, 근로 크루들이 시트를 업데이트 해주는 형식이 되려나요?
```
미용티슈 X 12, 주방세제 X 12, 물티슈 X 24, 닥터유 에너지바 X 1, 쓰레기봉투 X 50, 핸드워시 X 12
```

### 관리 방법 피드백
> 코치님들이 해당 비품 관리 시트를 통해 파악하는 것이 편하실지, 아니면 다른 구글폼을 만들어서 크루들로부터 부족한 재고 요청을 따로 받는게 더 편하실지 궁금합니다

일단은 비품 관리 시트를 통해 1차적으로 파악할 수 있도록 관리하고, 부족한 재고가 있다면 따로 이슈를 통해 요청해주시는 것이 편합니다. 🙂

**Comment by gaeun5744** [comment]
@woowahan-leah 


# 새로운 비품 관리 방식 제안
크루들이 구글폼을 제출해서 가져간 비품에 대해 기록하는 것은 다음과 같은 문제점이 있다고 생각했습니다.

1. 크루들이 잘못된 정보를 작성했을 때 시트 정보와 실제 수량에 차이가 발생할 수 있습니다.
2. 따라서, 근로 크루들이 일정 기간 마다 비품 재고를 확인해야합니다.
	- 즉, 구글 폼을 크루들이 작성하든 하지 않든 근로 크루들이 확인을 해야 한다는 사실은 동일합니다.

    위와 같은 사유로, 다음과 같이 새로운 비품 관리 방안을 전달하고자 합니다.


## 새로운 비품 관리 방안
- 일주일 간격으로, 우주먼지 팀이 남아있는 재고를 파악해서 스프레드 시트에 기록
	- 코치님들에게 공유하여 재고를 1차적으로 관리할 수 있도록 한다
- 재고 파악 후, 부족한 물품에 대해 추가 요청
## 문의 답변
>  다음과 같이 추가된 재고에 대하여 근로 크루들에게 안내드리면, 근로 크루들이 시트를 업데이트 해주는 형식이 되려나요?

네! 추가된 재고에 대해 알려주시면 우주 먼지 팀에서 업데이트 하겠습니다!
다만 일주일 간격으로 재고량을 파악하기 때문에, 직접 알려주시지 않아도 업데이트가 가능합니다.


## 제안 및 문의사항
- 부족한 물품 주문 요청 리마인더
코치님들이 부족한 물품을 쉽게 파악할 수 있도록, 비품 관리 시트와 함께 각 물품별 최소 필요 수량을 확인하여 리마인더를 보내드리고자 합니다.
(만약 비품 관리 시트만으로 관리가 충분하다고 생각되시면 알려주세요!)

	- `재고 추가 요청 기준` : 각 물품이 얼마나 남았을 때, 요청드리는 것이 좋은지 궁금합니다.
	
        ```
        예시: 휴지가 10개 이하로 남았을 때, 재고 추가 요청
        ```

	- `재고 추가 요청 방법` : 둘 중 어떤 방법으로 추가 요청을 받으시는 게 편하실지 궁금합니다.
		1. 6기 비품 관리 채널을 만들어서 요청을 받는 방법
		2. 깃허브 이슈를 생성해서 요청을 받는 방법

**Comment by wmakerjun** [comment]
# 추가 피드백 및 의견 제안
비품 관리에 대한 고민과 구체적인 실행 방안까지 공유해주셔서 넘넘 좋습니다!
저도 레아 의견이랑 비슷한데요. 물품을 가져 가는 사람들이 매번 작성하는게 매우 번거롭게 느껴질 것 같다는 생각이 들어요.
그래서 좀 더 쉽게, 하지만 중요한 재고 관리 파악을 잘할 수 있는 아이디어를 고민해봐도 좋을것 같은데요.

예를 들어 아래와 같은 방법들이 있을것 같아요. 신경은 덜 쓰면서, 1주일에 1번 정도의 체크만으로 관리할 수 있게 해보는건 어떨까요~? 만약 당번 제도 같은걸로 고민한다면한 사람이 신경쓰는 시간은 더 줄어들 것 같아요 ㅎㅎ
- 비품 창고에서, 물건을 가져가는 사람이 봤을 때 10개 이하인것 같다하면, 그 때 비품 물품 목록에 10개 이하 포스트잇이나 스티커를 붙인다던지
- 근로 크루들이 1주일에 한 번씩(월요일 같은날)에 비품과 같은 소모품들을 전체 체크하는 일정으로 정해서, 당번처럼 파악 후 필요한 재고 요청하기

이슈에 제안해준 아이디어 덕분에 비품 관리가 더 수월해질 것 같네요 💪🏻 화이팅입니닷!

**Comment by gaeun5744** [comment]
## 비품 관리 방안 확정 및 향후 계획

코치님들이 주신 피드백을 반영해서 다음과 같이 비품 관리를 진행하도록 하겠습니다!

1. 매주 월요일마다 전체 재고 수량 파악
    -  비품 관리 스프레드 시트에 업데이트
2. 물품이 10개 이하로 남을 경우, 깃허브 이슈를 통해 재고 추가 요청 


다음 주 월요일에 재고 점검 후 스프레드 시트를 공유하도록 하겠습니다!
추가적인 피드백이 있을 경우 언제든 알려주시면 감사하겠습니다 😊😊
