### ISSUE TITLE
[선릉 - 비품 관리] 9월 2주차 부족한 비품 현황

### ISSUE THREAD

**Issue by alstn113** [woowacourse/working-scholars#95]
# 개요
선릉캠퍼스 부족한 비품 현황 파악했습니다.

# 기간
2024.09.10 ~ 2024.09.24 (추석을 고려하여 2주로 잡았습니다.)

# 부족한 재고 현황

손세정제(4개), 물티슈(1개), 미용티슈(6개)로 수량이 부족하여 구매 요청드립니다.

<img width="316" alt="image" src="https://github.com/user-attachments/assets/9955ae28-7126-4c0f-bec4-6e3299ce878b">

[선릉 캠퍼스 비품 관리 현황 구글 시트](https://docs.google.com/spreadsheets/d/1km7F7B-eAfxM38jt6A9UT8JUK9vlBdVe53w3ct1QDTg/edit?gid=898395765#gid=898395765)

**Comment by woowahan-leah** [comment]
@alstn113 주문 요청 넣어두었으니 연휴 지나고 배송될거예요!
챙겨주셔서 감사해요 🙇

**Comment by alstn113** [comment]
2024년 9월 20일 16시 20분 택배 수령

모나리자 정사각미니 100매 X 6개
백셀 알카라인건전지 AAA 16개입 X 1개
백셀 알카라인건전지 AA 16개입 X 2개

**Comment by alstn113** [comment]
2024년 9월 23일 9시 40분 택배 수령

깨나라 99손소독물티슈 60개입 X 24개

**Comment by alstn113** [comment]
2024년 9월 26일 13시 40분 
손세정제
