### ISSUE TITLE
[선릉 - 도서관리] 도서 대여일지 도입 건의

### ISSUE THREAD

**Issue by gaeun5744** [woowacourse/working-scholars#96]
## 개요

선릉캠퍼스 도서 대여 일지 비치 건의

## 목적
- 누가 도서를 대여했는지에 대한 파악이 불분명
- 도서 분실 방지에 대안 부족

도서 대여일지를 통해 위의 문제를 해결하고자 합니다.

## 운영 계획

- [도서대여일지.pdf](https://drive.google.com/file/d/17WUH19fS-XnqNUCQ1UJUA6xtRBHxVuyx/view) 5장 출력하여 책장 근처에 비치
- 공지를 통해 선릉캠퍼스 도서 대여일지를 안내할 예정입니다.

## 기간
~ 2024.09.11 까지 확인해주시면 감사하겠습니다.

## 문의 사항
- 해당 건에 대한 코치님들의 피드백
- 대여일지를 5장을 출력 문의

**Comment by wmakerjun** [comment]
도서 대여일지 좋은것 같네요 👍🏻 
아마 크루들에게 낯설 수 있으니 placeholder처럼 예시 문구를 pdf파일에 작성해두면 더 좋을것 같네요~!

**Comment by gaeun5744** [comment]
넵! 공용우산 대여일지처럼, 출력 후 수기로 예시를 작성해 놓겠습니다.

**Comment by wmakerjun** [comment]
@gaeun5744 매버 수기로 예시를 작성해두려면 번거로울 것 같은데, 출력 용지 맨 위에 예시를 작성해두는건 어떨까요~?

**Comment by gaeun5744** [comment]
@wmakerjun 예시를 추가해서 [도서 대여일지.pdf](https://drive.google.com/file/d/1jy-dIfeuK4Gn8MfO3lkj_v87sDtfLJDn/view?usp=sharing) 를 새로 만들었습니다!

**Comment by woowahan-leah** [comment]
@gaeun5744 해당 일지로 출력해드렸어요! 혹시 또 도움 필요하시면 말씀해주세요~!
