### ISSUE TITLE
[선릉 - 만능팀] 제 2회 옹기종기 라이트닝 토크 기획

### ISSUE THREAD

**Issue by pakxe** [woowacourse/working-scholars#98]
# 개요
제 2회 옹기종기 라이트닝 토크 기획

# 기간
~ 2024.09.20

# 방법
- 자세한 사항은 회의록 내부에 작성했습니다.
- [09/10 회의록](https://github.com/woowacourse/working-scholars/wiki/9.10-%28%ED%99%94%29-%EB%A7%8C%EB%8A%A5%ED%8C%80-%ED%9A%8C%EC%9D%98%EB%A1%9D)

# 건의 사항

- 옹라토 준비-진행 과정을 짧은 영상 또는 카드뉴스로 편집해 우테코 인스타에 업로드할 수 있는지 알고 싶습니다.
- 다과 요청합니다. 
  - [립파이](https://www.coupang.com/vp/products/7284943818?itemId=18865107422&vendorItemId=85993997318&q=%EB%A6%BD%ED%8C%8C%EC%9D%B4&itemsCount=36&searchId=1e4e17020ee9423f95150cf420a4cca2&rank=2&isAddedCart=)
  - [비쵸비](https://www.coupang.com/vp/products/7764598919?itemId=17937926567&vendorItemId=85129874039&pickType=COU_PICK&q=%EB%B9%84%EC%B5%B8%EB%B9%84&itemsCount=36&searchId=cfbc19121c5b41bf8c71b9504baeda40&rank=0&isAddedCart=)
  - [망고 젤리](https://www.coupang.com/vp/products/7432045888?itemId=19305280552&vendorItemId=90747717789&pickType=COU_PICK&q=%EB%A7%9D%EA%B3%A0+%EC%A0%A4%EB%A6%AC&itemsCount=35&searchId=0238cf85b0e445a5a59085858e89cf4f&rank=1&isAddedCart=)

**Comment by woowahan-leah** [comment]
@pakxe 와 2회로 이어진 행사 넘 좋습니다! 👏 
문의에 대한 답변도 남깁니다.

## 옹라토 준비-진행 과정을 짧은 영상 또는 카드뉴스로 편집해 우테코 인스타에 업로드할 수 있는지 알고 싶습니다.
우테코 인스타는 최근에는 관리하고 있지 않아서 어려울 것 같아요.
다만 준비 과정을 촬영해서 유튜브에 업로드하는 것도 추천드립니다.
숏츠로 올리는 것은 어렵지만, 짧은 영상을 제작해서 업로드하는 것은 충분히 가능하니 참고해주세요.

## 다과 요청합니다.
🫡 지난 번보다 늘어났네요! ㅋㅋㅋ 선릉으로 주문해둘게요 ㅎㅎ

**Comment by woowahan-leah** [comment]
남겨주신 대로 다음과 같이 주문하겠습니다.

<img width="498" alt="image" src="https://github.com/user-attachments/assets/ef1a2564-e822-4a15-a50a-78a4772d9117">
